import React from 'react';
import {ROLE_STAGES,roleProgress,matchFeedback,importantMatch} from './career-role.mjs';
import {getTeam} from './league.mjs';
import {teamName} from './identity.mjs';
const labels={appearances:'本队记录出场',points:'位置贡献点',goodGames:'有效贡献且评分≥7的场次',titles:'参与赛季的冠军数'};
const pointRules={forward:'进球×2、助攻×1、射正×0.5（射正最多4次）。',midfielder:'助攻×2、关键传球×0.75（最多4次）、向前传球×0.1（最多8次）、成功传球×0.05（最多10次）、进球×0.5。',defender:'成功抢断×0.5（最多5次）、拦截×0.5（最多5次）、封堵×0.75（最多4次）。'};
export function RoleIdentity({career,season}){if(!career||!season)return null;return <p className="role-identity">{teamName(season,season.teamId)} · {roleProgress(career,season).name}</p>}
export function CareerRolePanel({career,season}){
 const role=roleProgress(career,season),others=Object.keys(career.clubProgress??{}).filter(id=>id!==season.teamId);
 return <section className="panel career-role"><div className="role-heading"><div><h2>你在球队的角色</h2><p>{teamName(season,season.teamId)} · 已记录{role.record.appearances}次出场</p></div><strong className="role-title">{role.name}</strong></div><ol className="role-ladder" aria-label="球队角色阶段">{ROLE_STAGES.map((name,i)=><li key={name} className={i===role.tier?'current':i<role.tier?'earned':''} aria-current={i===role.tier?'step':undefined}><span>{name}</span><small>{i<role.tier?'已达成':i===role.tier?'当前角色':'尚未达成'}</small></li>)}</ol>{role.next?<><h3>下一阶段：{role.next}</h3><p>同时达到以下条件，正式比赛结算后更新身份。</p><div className="role-requirements">{role.checks.map(r=><div key={r.key}><span>{labels[r.key]}</span><strong>{r.key==='points'?r.value.toFixed(1):r.value} / {r.target}</strong><progress aria-label={labels[r.key]} max={r.target} value={Math.min(r.target,r.value)}/><small>{r.complete?'已达成':`还需${+(r.target-r.value).toFixed(1)}`}</small></div>)}</div></>:<p>你已成为这家俱乐部的传奇。继续积累新的代表作与荣誉。</p>}<details className="role-rules"><summary>查看晋级规则与统计口径</summary><p>{pointRules[career.position]}单场位置贡献最多6点；出场次数、贡献点与高评分场次都只按本队记录累计。</p><p>稳定主力：6场、8点。球队核心：18场、30点、5场有效贡献且评分≥7。俱乐部传奇：42场、80点、12场有效贡献且评分≥7、至少1项冠军。</p><p>身份不附加能力奖励、不改变首发资格，也不降低已累计的进度。旧存档只回填保留且能确认球队归属的记录。换队按新队单独积累，旧队档案保留。</p><p>本队累计：{role.record.points.toFixed(1)}贡献点 · {role.record.goodGames}场高评分贡献 · {role.record.titles.length}项冠军。</p>{others.map(id=><p key={id}>旧队档案 · {teamName(season,id)}：{roleProgress(career,{...season,teamId:id}).name} · {career.clubProgress[id].appearances}场</p>)}</details></section>
}
export function FeedbackCard({stat,position,showPromotion=false}){if(!stat)return null;const feedback=matchFeedback(stat,position);return <section className="career-feedback"><h3>赛后观察</h3>{showPromotion&&stat.roleAfter>stat.roleBefore&&<p className="role-promotion" role="status">球队角色提升：{ROLE_STAGES[stat.roleBefore]} → {ROLE_STAGES[stat.roleAfter]}</p>}<dl><div><dt>本场贡献</dt><dd>{feedback.positive}</dd></div><div><dt>待改善之处</dt><dd>{feedback.concern}</dd></div><div><dt>下一场建议</dt><dd>{feedback.advice}</dd></div></dl><small>本场位置贡献 +{feedback.points.toFixed(2)}点 · 基于已记录事件，不推断比赛因果。</small></section>}
export function ImportantMatch({career,season,competition='league'}){const hint=importantMatch(career,season,competition);if(!hint)return null;return <section className="important-match"><h3>{hint.title}</h3><p>{hint.detail}</p></section>}
