import assert from 'node:assert/strict';
import {careerTimeline,careerSeasonSummary,selectSignature,signatureMatch} from './career-story.mjs';
import {createCareerPlayer,finishCareerMatch,toggleMatchMemory} from './career.mjs';
import {Match} from './engine.mjs';
import {createSeason,LEAGUES} from './league.mjs';
import {makeCareerSlot,exportBackup,importBackup} from './save-slots.mjs';
let p=createCareerPlayer('传奇测试',29,'midfielder');
assert.deepEqual(careerTimeline(p),[]);assert.equal(careerSeasonSummary(p,1),null);
const report=new Match().report();
p=finishCareerMatch(p,{goals:1,assists:1,keyPasses:3},[2,0],180,{report,opponent:'Arsenal',season:1,champion:true,final:true});
const events=careerTimeline(p);assert.equal(events.length,1);for(const label of ['首秀','首次进球','首次助攻','冠军之战','杯赛决赛','组织代表作 · 3+关键传球'])assert(events[0].labels.includes(label));
let chosen=selectSignature(p,1);assert.equal(signatureMatch(chosen).matchId,1);assert.equal(p.signatureMatchId,undefined);assert.equal(selectSignature(p,999).signatureMatchId,undefined);
const league=LEAGUES[0],season=createSeason(league.id,league.teams[0].id),backup=exportBackup({active:0,slots:[makeCareerSlot(season,chosen),null,null]});
assert.equal(importBackup(backup).slots[0].player.signatureMatchId,1);
const broken=JSON.parse(backup);broken.slots[0].player.signatureMatchId=999;assert.throws(()=>importBackup(JSON.stringify(broken)),/代表作/);
chosen=toggleMatchMemory(chosen,1);assert.equal(signatureMatch(chosen),null);assert.equal(chosen.signatureMatchId,undefined);assert(careerTimeline(chosen)[0].labels.includes('冠军之战'),'removing a collection must not erase recorded championship');
p=finishCareerMatch(p,{goals:2,keyPasses:1},[2,1],180,{season:2,opponent:'Liverpool'});
const first=careerSeasonSummary(p,1),second=careerSeasonSummary(p,2);assert.equal(first.goals,1);assert.equal(second.goals,2);assert.equal(first.appearances,1);assert.equal(first.contributions.find(([k])=>k==='keyPasses')[1],3);
const partial={...p,memories:[],history:p.history.filter(r=>r.season===2)};assert.equal(careerSeasonSummary(partial,1).contributions[0][1],null);assert(!careerTimeline(partial).some(r=>r.labels.includes('首次进球')),'never invent a first goal from truncated history');
const older={...p,history:p.history.map(({matchId,...r})=>r),seasonLedger:{1:{appearances:0,goals:0,ratingTotal:0}}};assert.equal(careerSeasonSummary(older,1).goals,1);assert.equal(careerTimeline(older).find(r=>r.matchId===1).labels.includes('首秀'),true);
const defender=finishCareerMatch(createCareerPlayer('后防',4,'defender'),{tackles:3,interceptions:2,blocks:1},[0,0],180);assert(careerTimeline(defender)[0].labels.includes('防守代表作 · 6+有效防守'));
console.log('Career timeline, signature persistence, season coverage and old-save checks passed.');
