export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Match {
 constructor({difficulty=1,duo=false,duration=180}={}){this.difficulty=difficulty;this.duo=duo;this.duration=duration;this.time=0;this.half=1;this.score=[0,0];this.shots=[0,0];this.passes=[0,0];this.possession=[0,0];this.selected=[1,7];this.ball={x:480,y:290,vx:0,vy:0,owner:null,lock:0,last:0};this.players=[];this.state='ready';this.event='准备开球';this.eventId=0;this.wait=0;this.charge=[0,0];this.reset(0);}
 direction(t){return (t===0?1:-1)*(this.half===1?1:-1)}
 reset(team){this.players=[];const formation=[[.06,.5],[.26,.29],[.26,.71],[.45,.25],[.45,.75],[.48,.5]];for(let t=0;t<2;t++)formation.forEach(([x,y],i)=>{let d=this.direction(t);this.players.push({x:60+(d===1?x:1-x)*840,y:60+y*460,hx:x,hy:y,t,i,dx:d,dy:0,stamina:1,cool:0,anim:0});});const owner=team*6+5;this.players[owner].x=480-this.direction(team)*9;this.players[owner].y=290;this.ball={x:480,y:290,vx:0,vy:0,owner,lock:0,last:team};this.selected=[5,11];this.charge=[0,0];}
 announce(text,wait=1.5){this.event=text;this.eventId++;this.wait=wait;}
 switch(t){const pool=this.players.map((p,i)=>({p,i})).filter(({p})=>p.t===t&&p.i!==0);pool.sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball));this.selected[t]=pool[0].i===this.selected[t]?pool[1].i:pool[0].i;}
 kick(id,shoot=false,power=.4){const p=this.players[id];if(this.ball.owner!==id)return;let dx=p.dx,dy=p.dy;let target=null;if(!shoot){let best=Infinity;this.players.forEach((q,j)=>{if(q.t!==p.t||j===id||q.i===0)return;const dist=distance(p,q);const align=((q.x-p.x)*dx+(q.y-p.y)*dy)/(dist||1);const rank=dist-align*200;if(rank<best){best=rank;target={q,j};}});if(target){dx=target.q.x-p.x;dy=target.q.y-p.y;this.selected[p.t]=target.j;}this.passes[p.t]++;}else{this.shots[p.t]++;const goalX=this.direction(p.t)===1?900:60;const toward=(goalX-p.x)*dx>0;if(toward&&Math.abs(dy)<.25){dx=goalX-p.x;dy=(290-p.y)*.45;}}
 const n=Math.hypot(dx,dy)||1,speed=shoot?350+power*400:330;this.ball.owner=null;this.ball.vx=dx/n*speed;this.ball.vy=dy/n*speed;this.ball.x=p.x+dx/n*15;this.ball.y=p.y+dy/n*15;this.ball.lock=.2;this.ball.last=p.t;p.cool=.6;this.charge[p.t]=0;}
 tackle(t){const id=this.selected[t],p=this.players[id];if(p.cool>0)return;const own=this.ball.owner;if(own!==null&&this.players[own].t!==t&&distance(p,this.players[own])<29){this.ball.owner=id;this.ball.last=t;this.players[own].cool=.6;}p.cool=.65;}
 restart(t,x,y,label){this.ball.owner=null;this.ball.x=x;this.ball.y=y;this.ball.vx=0;this.ball.vy=0;let pool=this.players.map((p,i)=>({p,i})).filter(({p})=>p.t===t&&p.i!==0).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball));pool[0].p.x=x;pool[0].p.y=y;this.ball.owner=pool[0].i;this.ball.last=t;this.selected[t]=pool[0].i;this.announce(label,1.1);}
 step(dt,inputs=[{},{}]){if(this.state!=='playing')return;dt=Math.min(dt,.04);if(this.wait>0){this.wait-=dt;return;}this.time+=dt;if(this.time>=this.duration){this.state='ended';this.announce('全场结束',0);return;}if(this.half===1&&this.time>=this.duration/2){this.half=2;this.reset(1);this.announce('下半场 · 交换场地',2);return;}this.ball.lock=Math.max(0,this.ball.lock-dt);
 const owner=this.ball.owner===null?null:this.players[this.ball.owner];if(owner)this.possession[owner.t]+=dt;
 const nearest=[0,1].map(t=>this.players.map((p,i)=>({p,i})).filter(({p})=>p.t===t&&p.i!==0).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball))[0].i);
 this.players.forEach((p,id)=>{p.cool=Math.max(0,p.cool-dt);let dx=0,dy=0,sprint=false;const human=(p.t===0||this.duo)&&this.selected[p.t]===id;const input=inputs[p.t]||{};if(human){dx=input.x||0;dy=input.y||0;sprint=!!input.sprint;if(input.shoot&&this.ball.owner===id)this.charge[p.t]=Math.min(1,this.charge[p.t]+dt*1.3);}else{let tx,ty;const d=this.direction(p.t),bx=this.ball.x,by=this.ball.y;if(p.i===0){tx=d===1?83:877;ty=clamp(by,247,333);if(Math.abs(bx-tx)<115){tx=clamp(bx,d===1?67:827,d===1?133:893);ty=clamp(by,210,370);}}else if(this.ball.owner===id){tx=d===1?865:95;ty=290+(p.hy-.5)*100;if(Math.abs(tx-p.x)<255&&p.cool===0){p.dx=d;p.dy=(290-p.y)/280;this.kick(id,true,.45+this.difficulty*.1);}else if(p.cool===0&&this.players.some(q=>q.t!==p.t&&distance(q,p)<26)&&this.players.some(q=>q.t===p.t&&(q.x-p.x)*d>70&&distance(q,p)<240)){p.dx=d;p.dy=0;this.kick(id,false);}}else if(id===nearest[p.t]&&(!owner||owner.t!==p.t)){tx=bx+this.ball.vx*.13;ty=by+this.ball.vy*.13;}else{const shift=(bx-480)*.25;tx=60+(d===1?p.hx:1-p.hx)*840+shift+(owner?.t===p.t?d*85:0);ty=60+p.hy*460+(by-290)*.19;}dx=(tx??p.x)-p.x;dy=(ty??p.y)-p.y;if(Math.hypot(dx,dy)<4){dx=0;dy=0;}}
 const n=Math.hypot(dx,dy);if(n>0){dx/=n;dy/=n;p.dx=dx;p.dy=dy;const boosted=sprint&&p.stamina>.04;const speed=(human?119:96+this.difficulty*9)*(boosted?1.5:1)*(this.ball.owner===id?.91:1);p.x=clamp(p.x+dx*speed*dt,64,896);p.y=clamp(p.y+dy*speed*dt,64,516);p.anim+=dt*speed/10;p.stamina=clamp(p.stamina+(boosted?-.29:.12)*dt,0,1);}else p.stamina=clamp(p.stamina+.18*dt,0,1);
 if(!human&&p.cool===0&&this.ball.owner!==null&&this.players[this.ball.owner].t!==p.t&&distance(p,this.ball)<18){const old=this.ball.owner;this.ball.owner=id;this.ball.last=p.t;this.players[old].cool=.6;p.cool=.3;}
 if(this.ball.owner===id&&p.i===0&&p.cool===0){p.cool=.7;this.kick(id,false);}
 });
 if(this.ball.owner!==null){const p=this.players[this.ball.owner];this.ball.x=p.x+p.dx*11;this.ball.y=p.y+p.dy*11;}else{const b=this.ball;b.x+=b.vx*dt;b.y+=b.vy*dt;const drag=Math.exp(-.62*dt);b.vx*=drag;b.vy*=drag;if(b.lock<=0){const catcher=this.players.findIndex(p=>p.cool<=0&&distance(p,b)<(p.i===0?19:11));if(catcher!==-1){b.owner=catcher;b.last=this.players[catcher].t;this.players[catcher].cool=.25;}}}
 const b=this.ball;if(b.x<60||b.x>900){if(b.y>245&&b.y<335){const t=this.direction(0)===(b.x>900?1:-1)?0:1;this.score[t]++;this.reset(1-t);this.announce(t===0?'蓝队进球！':'红队进球！',2.6);}else{const defend=this.direction(0)===(b.x<60?1:-1)?0:1;if(b.last===defend)this.restart(1-defend,b.x<60?68:892,b.y<290?68:512,'角球');else this.restart(defend,b.x<60?105:855,290,'球门球');}}else if(b.y<60||b.y>520)this.restart(1-b.last,clamp(b.x,80,880),b.y<60?66:514,'边线球');
 }
}
