import {recordFrame,freezeGoal} from './replay.mjs';
import {tacticalPlan} from './tactics.mjs';
import {objectiveFor} from './experience.mjs';
import {FIELD} from './field.mjs';
export {FIELD} from './field.mjs';
export const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
export const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
const formation = [[.035,.5],[.23,.28],[.23,.72],[.38,.25],[.38,.75],[.38,.5]];
export const keeperMistakeChance = (power,offset,range,difficulty,skill=60,strength=1,keeperSkill=60) => clamp(.10+power*.14+clamp(offset/48,0,1)*.14+clamp((230-range)/230,0,1)*.10+(skill-60)*.0015-(keeperSkill-60)*.002-difficulty*.025-(strength-1)*.15,.04,.47);

export function shootoutWinner(ours,theirs,attempt){const oursLeft=Math.max(0,5-Math.ceil(attempt/2)),theirLeft=Math.max(0,5-Math.floor(attempt/2));return (attempt<10?(ours>theirs+theirLeft||theirs>ours+oursLeft):(attempt%2===0&&ours!==theirs))?(ours>theirs?0:1):null}

export class Match {
  constructor({difficulty=1, duration=180, teams=['蓝湾 FC','赤焰联队'], strength=[1,1], tactic='balanced', styles=['balanced','balanced'], careerIndex=null, careerNumber=null, careerLook=null, careerAttributes=null,careerStyle=null,playerAttributes=null,playerIds=null,playerNumbers=null,round=0}={}) {
    Object.assign(this,{difficulty,duration,teams,strength,tactic,styles,careerIndex,careerNumber,careerLook,careerAttributes,careerStyle,playerAttributes,playerIds,playerNumbers,round});this.objective=careerIndex===null?null:objectiveFor(careerIndex===5?'forward':careerIndex===3?'midfielder':'defender',round,duration);
    this.attackStarted=[-10,-10];this.giveGo=null;this.time=0; this.half=1; this.score=[0,0]; this.shots=[0,0]; this.onTarget=[0,0]; this.passes=[0,0]; this.crosses=[0,0]; this.fouls=[0,0]; this.saves=[0,0]; this.tackles=[0,0]; this.yellows=[0,0]; this.reds=[0,0]; this.possession=[0,0];
    this.stats=Array.from({length:12},()=>({goals:0,assists:0,shots:0,shotsOnTarget:0,passes:0,passesCompleted:0,crosses:0,tackles:0,touches:0,fouls:0,yellows:0,reds:0,saves:0,distance:0,possession:0,headers:0,bicycles:0,forwardPasses:0,interceptions:0,tackleAttempts:0,playingSeconds:0,keyPasses:0,blocks:0,turnovers:0,crossesCompleted:0,carryDistance:0,headerGoals:0,bicycleGoals:0,penaltyGoals:0}));
    this.shotLog=[];this.matchEvents=[];this.heatClock=0;this.heat=Array.from({length:12},()=>Array.from({length:4},()=>Array(96).fill(0)));this.players=[];this.selected=[5,11];this.state='ready';this.event='准备开球';this.eventId=0;this.wait=0;this.charge=0;this.pointer=null;this.pendingShot=null;this.penalty=null;this.events=[];this.noticeTime=0;this.shootoutMode=false;this.lastPasser=null;this.lastStriker=null;this.reset(0);
  }
  eventRecord(type,id,extra={}){this.matchEvents.push({type,player:id,team:this.players[id]?.t??0,minute:Math.min(90,Math.floor(this.time/this.duration*90)),...extra})}
  recordShot(id,type='normal',power=null,target=null){if(this.shootoutMode)return;this.resolveShot('whistle');const p=this.players[id],d=this.direction(p.t),pressured=this.players.some((q,j)=>q.t!==p.t&&this.active(j)&&distance(p,q)<55),x=d===1?(p.x-FIELD.left)/FIELD.width:(FIELD.right-p.x)/FIELD.width,y=(p.y-FIELD.top)/FIELD.height,quality=x>.83&&Math.abs(y-.5)<.2&&!pressured?'高':x>.65&&!pressured?'中':'低',shot={id:this.shotLog.length,player:id,team:p.t,minute:Math.min(90,Math.floor(this.time/this.duration*90)),half:this.half,x:clamp(x,0,1),y:clamp(y,0,1),type,pressured,quality,outcome:'pending',power,speed:Math.hypot(this.ball.vx,this.ball.vy),distance:Math.hypot((d===1?FIELD.right:FIELD.left)-p.x,FIELD.center-p.y)/10,aim:target?{x:clamp((d===1?target.x-FIELD.left:FIELD.right-target.x)/FIELD.width,0,1),y:clamp((target.y-FIELD.top)/FIELD.height,0,1)}:null,trajectory:{x:d*this.ball.vx,y:this.ball.vy},keeper:this.players.findIndex(q=>q.t!==p.t&&q.i===0)};this.shotLog.push(shot);this.ball.shotId=shot.id;this.eventRecord('shot',id,{shotId:shot.id});if(this.lastPasser!==null&&this.lastPasser!==id&&this.players[this.lastPasser]?.t===p.t)this.stats[this.lastPasser].keyPasses++}
  resolveShot(outcome,by=null){const shot=this.shotLog[this.ball.shotId];if(shot&&shot.outcome==='pending'){shot.outcome=outcome;shot.resolvedBy=by;shot.end={x:clamp((this.direction(shot.team)===1?this.ball.x-FIELD.left:FIELD.right-this.ball.x)/FIELD.width,0,1),y:clamp((this.ball.y-FIELD.top)/FIELD.height,0,1)};this.shotFeedback={...shot};this.shotFeedbackTime=2}}
  report(){return {version:1,careerIndex:this.careerIndex,...(this.playerIds?{playerIds:[...this.playerIds]}:{}),numbers:this.players.map((p,id)=>this.playerNumbers?.[id]??(this.playerNumbers?.[id]??(id===this.careerIndex?this.careerNumber:p.i===0?1:p.i+5))),teams:[...this.teams],score:[...this.score],duration:this.duration,shots:this.shotLog.map(s=>({...s,outcome:s.outcome==='pending'&&this.state==='ended'?'whistle':s.outcome})),events:[...this.matchEvents],heat:this.heat.map(rows=>rows.map(row=>row.map(n=>+n.toFixed(1)))),stats:structuredClone(this.stats)}}
  skill(id,field){return this.careerIndex===id?this.careerAttributes?.[field]??this.playerAttributes?.[id]?.[field]??60:this.playerAttributes?.[id]?.[field]??60}
  direction(t){return (t===0?1:-1)*(this.half===1?1:-1)}
  active(id){return !this.stats[id].reds}
  announce(s,wait=0){this.event=s;this.eventId++;this.wait=wait;this.noticeTime=2;this.events.push({minute:Math.min(90,Math.floor(this.time/this.duration*90)),text:s});if(this.events.length>20)this.events.shift()}
  aiLevel(t){return t===0?1:this.difficulty}
  queueAiKick(id,shoot,power,target,lead=false){if(!shoot){this.kick(id,false,power,target,lead);return [0,0]}this.players[id].aiKick={shoot,power,target,lead,started:this.time,at:this.time+.08};return [0,0]}
  aim(id,target){const p=this.players[id],fallback={x:this.direction(p.t)===1?FIELD.right:FIELD.left,y:FIELD.center};return target&&distance(p,target)>=10?target:fallback}
  passOption(id,targetId=null,lead=false,tactical=false){const p=this.players[id],d=this.direction(p.t),rivals=this.players.filter((q,j)=>q.t!==p.t&&this.active(j));return this.players.map((q,j)=>{const travel=lead?clamp(distance(p,q)/360,.1,.4):0,x=clamp(q.x+(q.vx??0)*travel,FIELD.left+12,FIELD.right-12),y=clamp(q.y+(q.vy??0)*travel,FIELD.top+12,FIELD.bottom-12),vx=x-p.x,vy=y-p.y,n=vx*vx+vy*vy;const lane=Math.min(...rivals.map(r=>{const u=clamp(((r.x-p.x)*vx+(r.y-p.y)*vy)/(n||1),0,1);return Math.hypot(r.x-p.x-u*vx,r.y-p.y-u*vy)}));return {q,j,x,y,lane,receiver:Math.min(...rivals.map(r=>distance(q,r))),progress:d*vx}}).filter(o=>o.q.t===p.t&&(targetId===null||o.j===targetId)&&o.j!==id&&o.q.i!==0&&this.active(o.j)&&distance(p,o.q)>25&&distance(p,o.q)<450&&o.lane>(p.i===0?36:17)&&o.receiver>(p.i===0?48:20)&&(p.i!==0||o.progress>50)).sort((a,b)=>{const plan=tactical?this.teamPlan(p.t):null,weight=plan?(plan.mentality==='protect'?.35:plan.style==='counter'?1.15:plan.style==='press'?.9:1):.75,score=o=>distance(p,o.q)-o.progress*weight-(lead?Math.min(o.receiver,80)*.6-Math.max(0,-o.progress)*.8:0)-(tactical?Math.min(o.lane,100)*.35:0)+Math.max(0,70-Math.min(o.y-FIELD.top,FIELD.bottom-o.y))*.4+(Math.abs((d===1?FIELD.right:FIELD.left)-p.x)<280?Math.max(0,Math.abs(o.y-FIELD.center)-Math.abs(p.y-FIELD.center))*.12:0);return score(a)-score(b)})[0]??null}
  available(t){return [5,4,3,2,1].map(i=>t*6+i).find(id=>this.active(id))}
  teamPlan(t){return tacticalPlan(t===0?this.tactic:this.styles[t],this.score,t,this.time/this.duration,this.players.filter((p,id)=>p.t===t&&p.i!==0&&this.active(id)).length)}
  pressers(t){const base=t===0?(this.tactic==='press'?3:this.tactic==='counter'?1:2):clamp([1,1,2,3][this.difficulty]+(this.styles[1]==='press'?1:this.styles[1]==='counter'?-1:0),1,5);const plan=this.teamPlan(t),available=this.players.filter((p,id)=>p.t===t&&p.i!==0&&this.active(id)).length;return clamp(base+plan.press,1,Math.max(1,available-(plan.shortHanded?2:1)))}
  shotTarget(id){const p=this.players[id],gx=this.direction(p.t)===1?FIELD.right:FIELD.left,range=Math.abs(gx-p.x);if(range>[260,270,280,290][this.aiLevel(p.t)]*this.strength[p.t]||Math.abs(p.y-FIELD.center)>range*.65+25)return null;const keeper=this.players.find(q=>q.t!==p.t&&q.i===0);return [FIELD.center-30,FIELD.center+30,FIELD.center].sort((a,b)=>Math.abs(b-keeper.y)-Math.abs(a-keeper.y)).map(y=>({x:gx,y})).find(aim=>!this.players.some((q,j)=>{const u=(q.x-p.x)/(gx-p.x||1);return q.t!==p.t&&q.i!==0&&this.active(j)&&u>0&&u<.88&&Math.abs(q.y-(p.y+(aim.y-p.y)*u))<18}))??null}
  shotOpen(id){return !!this.shotTarget(id)}

  keeperTarget(p,b){const d=this.direction(p.t),goalX=d===1?FIELD.left:FIELD.right,baseX=goalX+d*29;if(p.cool>0)return [p.x,p.y];if(b.kind==='shot'&&p.t!==b.last){if(b.keeperDelay>0)return [p.x,p.y];const eta=(goalX-b.x)/(b.vx||1),projected=b.y+b.vy*eta;if(!p.diveUsed&&eta>0&&eta<.45&&Math.abs(projected-p.y)>10){p.diveUsed=true;p.dive=.26;p.diveAt=this.time;p.diveSide=Math.sign(projected-p.y)||1;p.diveY=clamp(projected+(b.keeperOffset??0),FIELD.center-54,FIELD.center+54)}return [baseX,p.diveUsed?p.diveY:clamp(projected,FIELD.center-48,FIELD.center+48)]}return [baseX,clamp(FIELD.center+(b.y-FIELD.center)*.35,FIELD.center-30,FIELD.center+30)]}
  canCollect(p,b){if(p.i!==0)return b.z<9&&distance(p,b)<12;const shot=b.kind==='shot'&&b.last!==p.t,diving=shot&&p.dive>0&&p.cool===0&&!(b.keeperDelay>0);return b.z<(shot?24:9)&&Math.abs(p.x-b.x)<(shot?20:18)&&Math.abs(p.y-b.y)<(shot?(diving?24:10):20)}
  reset(t){this.giveGo=null;this.setPiece=null;const f=FIELD,stamina=this.players.map(p=>p.stamina);this.players=[];for(let side=0;side<2;side++)formation.forEach(([fx,fy],i)=>{let d=this.direction(side);this.players.push({x:f.left+(d===1?fx:1-fx)*(f.right-f.left),y:f.top+fy*(f.bottom-f.top),hx:fx,hy:fy,t:side,i,dx:d,dy:0,stamina:stamina[side*6+i]??1,cool:0,anim:0,sprinting:false,settle:0,tackleWindup:0,tackleTarget:null,tackleRecovery:0,decisionCool:0,heldSince:this.time,avoidTime:0,avoidSide:0,vx:0,vy:0,dive:0,diveUsed:false,diveY:f.center,diveAt:null,diveSide:1,saveAt:null,saveKind:null})});const id=this.available(t);this.players[id].x=f.mid-this.direction(t)*10;this.players[id].y=f.center;this.ball={x:f.mid,y:f.center,z:0,vx:0,vy:0,vz:0,owner:id,lock:0,last:t,kind:null,source:null};this.selected=[this.careerIndex??this.available(0),this.available(1)];if(this.careerIndex===null||t===1)this.selected[t]=id;this.charge=0;this.pendingShot=null;this.penalty=null;this.kickoffGrace=0;this.kickoffId=id}
  switch(t){if(t===0&&this.careerIndex!==null)return;const pool=this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball));this.selected[t]=pool[0].id===this.selected[t]&&pool[1]?pool[1].id:pool[0].id;delete this.ball.controlSource;this.charge=0;this.pendingShot=null}
  release(id,vx,vy,vz=0,kind='pass'){const p=this.players[id],n=Math.hypot(vx,vy)||1;this.ball={startX:p.x,x:p.x+vx/n*16,y:p.y+vy/n*16,z:vz?5:0,vx,vy,vz,owner:null,lock:.2,last:p.t,kind,source:id};this.lastStriker=id;this.kickoffGrace=0;this.kickoffId=null;this.setPiece=null;if(kind!=='shot'&&p.t===0&&this.careerIndex===null&&this.selected[0]===id)this.ball.controlSource=id;p.cool=.65;p.kickAt=this.time;p.kickType=kind;if(p.t===0)this.charge=0;if(kind!=='shot')this.lastPasser=id;if(this.penalty)this.penalty=null}
  shoot(power=.42,target=this.pointer,bicycle=false){this.pendingShot=null;power=Math.max(.42,power);if(this.aerial(this.selected[0],bicycle,target)||this.kick(this.selected[0],true,power,target))return true;const b=this.ball;if(b.owner!==null||b.kind!=='pass'||b.last!==0||b.z>=9)return false;let id=this.selected[0];if(b.controlSource===id){const receiver=this.players.map((p,j)=>({p,j})).filter(({p,j})=>p.t===0&&p.i!==0&&j!==b.source&&this.active(j)).sort((a,c)=>distance(a.p,b)-distance(c.p,b))[0];if(receiver)id=receiver.j}const p=this.players[id];if(!this.active(id)||distance(p,b)>32||b.vx*(p.x-b.x)+b.vy*(p.y-b.y)<=0)return false;this.pendingShot={id,power,target:target?{...target}:null,left:.12};return true}
  actionHint(kind='shoot'){const id=this.selected[0],p=this.players[id];if(!this.active(id))return '你已被罚下，等待本场结束';if(kind==='cross'&&this.penalty)return '点球时不能传中';if(this.ball.owner===id)return '';if(this.ball.owner===null&&this.ball.z>=9){if(distance(p,this.ball)>25)return '空中球太远，先移动到落点附近';if(p.cool>0)return '动作恢复中，稍后再争顶';return '争顶时机未到，等待足球落近'}return this.careerIndex!==null?'当前无球，按 K 呼叫队友传球':'当前无球，按 Q 切人或靠近足球'}
  passFailure(id,targetId=null){const p=this.players[id],q=this.players[targetId];if(q){const n=distance(p,q);if(n<=25)return '距离太近，先拉开接应空间';if(n>=450)return '传球距离太远，先靠近持球队友';if(this.players.some((r,j)=>r.t!==p.t&&this.active(j)&&distance(r,q)<=20))return '接球人被盯住，先跑出空位'}return '传球线路受阻，换个角度寻找接应'}
  requestPass(t=0){const id=this.ball.owner,target=this.selected[t],p=this.players[id],q=this.players[target];if(!this.active(target)){this.announce('你已被罚下，等待本场结束');return false}if(id===null||!p||p.t!==t){this.announce(id===null?'足球尚未被控制，先靠近接应':'对方持球，先参与防守');return false}if(id===target)return false;const option=this.passOption(id,target);if(!option){this.announce(this.passFailure(id,target));return false}return this.kick(id,false,.4,target)}
  kick(id,shoot=false,power=.4,target=null,lead=false){const p=this.players[id],wasPenalty=!!this.penalty;if(this.ball.owner!==id||!this.active(id))return false;const d=this.direction(p.t);let dx=p.dx,dy=p.dy,receivePoint=null;if(!shoot&&!this.penalty){const option=this.passOption(id,typeof target==='number'?target:null,lead);if(option){dx=option.x-p.x;dy=option.y-p.y;target=option.j;receivePoint={x:option.x,y:option.y}}else if(p.i===0){const rivals=this.players.filter((q,j)=>q.t!==p.t&&this.active(j));dx=d*360;dy=rivals.filter(q=>q.y<FIELD.center).length<=rivals.length/2?-170:170}else{if(p.t===0&&this.selected[0]===id)this.announce(this.passFailure(id,typeof target==='number'?target:null));p.cool=.2;return false}this.passes[p.t]++;this.stats[id].passes++}else{shoot=true;this.shots[p.t]++;this.stats[id].shots++;const gx=d===1?FIELD.right:FIELD.left;if(p.t===0&&this.selected[0]===id){const aim=this.aim(id,target);dx=aim.x-p.x;dy=aim.y-p.y;if(Math.hypot(dx,dy)<10){dx=gx-p.x;dy=FIELD.center-p.y}}else if(target&&typeof target==='object'){dx=target.x-p.x;dy=target.y-p.y}else if(this.penalty){dx=gx-p.x;dy=FIELD.center+(p.dy<-.2?-33:p.dy>.2?33:p.i%2?31:-31)-p.y}else if(dx*d>0&&Math.abs(dy)<.25){dx=gx-p.x;dy=FIELD.center+(p.y<FIELD.center?-28:28)-p.y}}const n=Math.hypot(dx,dy)||1,skill=this.skill(id,shoot?'shooting':'passing'),mult=.85+(skill??60)/400,speed=(shoot?410+clamp(power,0,1)*340:360)*mult*(id===this.careerIndex?(shoot?(this.careerStyle==='runner'?.96:this.careerStyle==='finisher'&&Math.abs((d===1?FIELD.right:FIELD.left)-p.x)<180?1.04:1):['engine','stopper'].includes(this.careerStyle)?.96:1):1),pressure=this.players.some((q,j)=>q.t!==p.t&&this.active(j)&&distance(q,p)<55),spread=(shoot?(pressure?.03:0):.012)*(100-(skill??60))/40*(id===this.careerIndex&&(shoot?this.careerStyle==='finisher'&&Math.abs((d===1?FIELD.right:FIELD.left)-p.x)<180:['creator','ballplayer'].includes(this.careerStyle))?.65:1),angle=Math.atan2(dy,dx)+(Math.random()-.5)*spread;this.release(id,Math.cos(angle)*speed,Math.sin(angle)*speed,0,shoot?'shot':'pass');if(!shoot&&typeof target==='number'){this.ball.receiver=target;this.ball.receivePoint=receivePoint;if(p.i!==0&&this.direction(p.t)*(this.players[target].x-p.x)>-45)this.giveGo={id,receiver:target,until:this.time+2.4,x:clamp(p.x+this.direction(p.t)*120,FIELD.left+30,FIELD.right-30),y:clamp(p.y+(p.y<this.players[target].y?-45:45),FIELD.top+25,FIELD.bottom-25)}}if(shoot){this.recordShot(id,wasPenalty?'penalty':'normal',power,this.aim(id,typeof target==='object'?target:null));this.keeperReaction(id,power,skill??60)}return true}
  keeperReaction(id,power,skill=60){const p=this.players[id],b=this.ball,gx=this.direction(p.t)===1?FIELD.right:FIELD.left,goalY=b.y+b.vy/(b.vx||this.direction(p.t))*(gx-b.x),chance=keeperMistakeChance(power,Math.abs(goalY-FIELD.center),Math.abs(gx-p.x),this.aiLevel(1-p.t),skill,this.strength[1-p.t],this.skill((1-p.t)*6,'goalkeeping'));b.keeperError=Math.random()<chance;b.keeperDelay=[.11,.07,.045,.025][this.aiLevel(1-p.t)]+Math.random()*.14+(b.keeperError?.18:0);b.keeperOffset=(Math.random()-.5)*(b.keeperError?32:8);const keeper=this.players.find(q=>q.t!==p.t&&q.i===0);keeper.dive=0;keeper.diveUsed=false;keeper.diveAt=null;keeper.saveAt=null;}
  parry(id){const p=this.players[id],b=this.ball,gx=this.direction(p.t)===1?FIELD.left:FIELD.right,eta=(gx-b.x)/(b.vx||1);if(!(eta>0&&Math.abs(b.y+b.vy*eta-FIELD.center)<48))return false;this.resolveShot('saved',id);this.saves[p.t]++;this.stats[id].saves++;this.onTarget[b.last]++;if(b.source!==null)this.stats[b.source].shotsOnTarget++;const side=Math.sign(b.y-p.y)||1;p.diveSide=side;this.ball={x:p.x+this.direction(p.t)*24,y:p.y+side*18,z:3,vx:this.direction(p.t)*150,vy:side*170,vz:45,owner:null,lock:.15,last:p.t,kind:'parry',source:null};p.cool=.65;p.dive=0;p.saveAt=this.time;p.saveKind='parry';this.lastPasser=null;this.announce('门将扑出，争取补射！');return true}
  cross(id){const p=this.players[id];if(this.ball.owner!==id||this.penalty||!this.active(id))return false;const d=this.direction(p.t),pool=this.players.map((q,j)=>({q,j})).filter(({q,j})=>q.t===p.t&&j!==id&&q.i!==0&&this.active(j)&&(q.x-p.x)*d>25).sort((a,b)=>Math.abs(a.q.y-FIELD.center)-Math.abs(b.q.y-FIELD.center));const q=pool[0]?.q??{x:clamp(p.x+d*220,FIELD.left+30,FIELD.right-30),y:FIELD.center};const dx=q.x-p.x,dy=q.y-p.y,n=Math.hypot(dx,dy)||1,skill=this.skill(id,'passing'),speed=clamp(n/.82,165,520)*(.85+(skill??60)/400);this.crosses[p.t]++;this.passes[p.t]++;this.stats[id].passes++;this.stats[id].crosses++;this.release(id,dx/n*speed,dy/n*speed,130,'cross');return true}
  aerial(id,bicycle=false,target=null){const p=this.players[id],b=this.ball;if(!this.active(id)||p.cool>0||b.owner!==null||b.z<9||b.z>37||distance(p,b)>25)return false;if(b.kind==='cross'&&b.source!==null&&b.source!==id&&this.players[b.source]?.t===p.t){this.stats[b.source].passesCompleted++;this.stats[b.source].crossesCompleted++;if(this.direction(p.t)*(p.x-(b.startX??p.x))>45)this.stats[b.source].forwardPasses++}const gx=this.direction(p.t)===1?FIELD.right:FIELD.left,gy=FIELD.center+(p.y<FIELD.center?-23:23),aim=p.t===0&&target&&Math.hypot(target.x-p.x,target.y-p.y)>=10?target:{x:gx,y:gy},dx=aim.x-p.x,dy=aim.y-p.y,n=Math.hypot(dx,dy),speed=bicycle?760:620;this.shots[p.t]++;this.stats[id].shots++;this.stats[id][bicycle?'bicycles':'headers']++;b.vx=dx/n*speed;b.vy=dy/n*speed;b.vz=bicycle?25:4;b.lock=.18;b.last=p.t;b.kind='shot';b.source=id;this.lastStriker=id;this.kickoffGrace=0;p.cool=.65;p.kickAt=this.time;p.kickType=bicycle?'bicycle':'header';p.anim+=12;this.recordShot(id,bicycle?'bicycle':'header',bicycle?1:.6,aim);this.keeperReaction(id,bicycle?1:.6,this.skill(id,'shooting'));this.announce(bicycle?'倒钩射门！':'头球攻门！');return true}
  takeBall(id){if(this.ball.last!==this.players[id].t)this.attackStarted[this.players[id].t]=this.time;const former=this.ball.owner,p=this.players[id],shooter=this.lastStriker,b=this.ball,gx=this.direction(p.t)===1?FIELD.left:FIELD.right,eta=(gx-b.x)/(b.vx||1),onGoal=eta>0&&Math.abs(b.y+b.vy*eta-FIELD.center)<48,saved=p.i===0&&this.ball.kind==='shot'&&this.ball.last!==p.t&&onGoal,completed=former===null&&this.ball.kind!=='shot'&&this.ball.source!==null&&this.players[this.ball.source]?.t===p.t;if(former!==null&&former!==id){this.players[former].cool=.6;if(this.players[former].t!==p.t)this.stats[former].turnovers++}if(former===null&&b.source!==null&&this.players[b.source]?.t!==p.t&&b.kind!=='shot')this.stats[b.source].turnovers++;if(b.kind==='shot'&&b.last===p.t)this.resolveShot('whistle',id);if(b.kind==='shot'&&b.last!==p.t){this.resolveShot(p.i===0?(onGoal?'saved':'wide'):'blocked',id);if(p.i!==0)this.stats[id].blocks++}if(completed){if(this.careerIndex===null&&p.t===0&&p.i!==0&&b.controlSource===this.selected[0])this.selected[0]=id;if(b.kind==='cross')this.stats[b.source].crossesCompleted++;this.stats[this.ball.source].passesCompleted++;if(this.direction(p.t)*(p.x-(this.ball.startX??p.x))>45)this.stats[this.ball.source].forwardPasses++}if(former===null&&this.ball.source!==null&&this.players[this.ball.source]?.t!==p.t&&this.ball.kind!=='shot')this.stats[id].interceptions++;if(p.i===0&&b.kind==='shot'&&b.last!==p.t){p.saveAt=this.time;p.saveKind='catch';p.diveSide=Math.sign(b.y-p.y)||p.diveSide||1}if(saved){this.saves[p.t]++;this.stats[id].saves++;if(shooter!==null){this.stats[shooter].shotsOnTarget++;this.onTarget[this.players[shooter].t]++}this.event='门将扑救！';this.eventId++;p.anim+=9}this.stats[id].touches++;delete this.ball.shotId;this.ball.owner=id;this.kickoffId=null;this.ball.receiver=null;this.ball.z=0;this.ball.vz=0;this.ball.last=p.t;this.ball.kind=null;this.ball.source=null;p.cool=p.i===0?.6:.22;p.decisionCool=0;p.heldSince=this.time;p.settle=former===null?.18:0;p.tackleTarget=null;p.tackleWindup=0;p.dive=0;if(this.players[this.lastPasser]?.t!==p.t)this.lastPasser=null;this.charge=0}
  restart(t,x,y,label,wait=1.1){this.pendingShot=null;const pool=this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)).sort((a,b)=>distance(a.p,{x,y})-distance(b.p,{x,y}));const id=pool[0].id;this.players[id].x=x-this.direction(t)*10;this.players[id].y=y;this.ball={x,y,z:0,vx:0,vy:0,vz:0,owner:id,lock:0,last:t,kind:null,source:null};if(this.careerIndex===null||t!==0)this.selected[t]=id;this.setPiece=t===0&&this.careerIndex===null&&/角球|边线球/.test(label)?{id,at:this.time}:null;this.lastPasser=null;this.announce(label,wait)}
  foul(id,victim){const p=this.players[id],stats=this.stats[id];this.fouls[p.t]++;stats.fouls++;const card=stats.fouls%2===0;this.eventRecord('foul',id);if(card){this.yellows[p.t]++;stats.yellows++}if(card)this.eventRecord('yellow',id);const red=stats.yellows>=2;if(red)this.eventRecord('red',id);if(red){stats.reds=1;this.reds[p.t]++;if(this.careerIndex===null||p.t!==0)this.selected[p.t]=this.available(p.t)}const gx=this.direction(p.t)===1?FIELD.left:FIELD.right;const contact=this.players[victim],penalty=Math.abs(contact.x-gx)<135&&Math.abs(contact.y-FIELD.center)<125,t=this.players[victim].t,label=`${p.t===0?'己方':'对方'} ${this.playerNumbers?.[id]??(id===this.careerIndex?this.careerNumber:p.i===0?1:p.i+5)}号 · ${red?'两黄变红':card?'黄牌':'未出牌'}`;if(penalty){this.restart(t,gx===FIELD.left?FIELD.left+120:FIELD.right-120,FIELD.center,`点球！${label}`,1.5);this.penalty={team:t}}else this.restart(t,clamp(p.x,FIELD.left+20,FIELD.right-20),clamp(p.y,FIELD.top+20,FIELD.bottom-20),`犯规 · ${label}`,1.2)}
  attemptTackle(id,automatic=false){const p=this.players[id];if(!p||!this.active(id)||p.cool>0||this.penalty)return false;this.tackles[p.t]++;this.stats[id].tackleAttempts++;p.tackleAt=this.time;p.cool=.72;p.tackleRecovery=.28;const holder=this.ball.owner,skill=this.skill(id,'defense'),reach=(p.i===0?22:31)+(skill-60)*.18+(id===this.careerIndex?(this.careerStyle==='stopper'?3:this.careerStyle==='ballplayer'?-2:0):0);if(holder===null)return false;const q=this.players[holder];if(q.t===p.t||distance(p,q)>=reach||q.settle>0)return false;const exposure=(p.x-q.x)*q.dx+(p.y-q.y)*q.dy;if(p.i!==0&&exposure<-12){if(automatic&&Math.random()>.08)return false;this.foul(id,holder);return true}if(Math.random()>clamp((exposure<0?.40:.85)+(skill-60)*.003,.2,.95))return false;this.stats[id].tackles++;this.takeBall(id);p.cool=.6;p.tackleRecovery=0;return true}
  tackle(t){return this.attemptTackle(this.selected[t])}
  beginShootoutKick(team){this.shootoutMode=true;this.state='playing';this.half=1;this.wait=0;this.shotOutcome=null;this.shotElapsed=0;this.reset(team);this.shootoutMode=true;const id=team===0&&this.careerIndex!==null?this.careerIndex:this.available(team),d=this.direction(team),gx=d===1?FIELD.right:FIELD.left;this.selected[team]=id;this.players.forEach((p,j)=>{p.x=FIELD.mid;p.y=FIELD.top-80;if(j===id){p.x=gx-d*120;p.y=FIELD.center}if(p.i===0){p.x=p.t===team?(d===1?FIELD.left:FIELD.right):gx-d*22;p.y=FIELD.center}});this.ball={x:this.players[id].x+d*11,y:FIELD.center,z:0,vx:0,vy:0,vz:0,owner:id,lock:0,last:team,kind:null,source:null};this.penalty={team};}
  goal(t){if(this.shootoutMode){this.shotOutcome=t===this.ball.last;this.state='ended';return}this.goalCelebrant=this.ball.owner??this.lastStriker;if(this.ball.shotId===undefined&&this.goalCelebrant!==null&&this.players[this.goalCelebrant]?.t===t)this.recordShot(this.goalCelebrant);this.resolveShot('goal');this.eventRecord('goal',this.ball.owner??this.lastStriker,{shotId:this.ball.shotId});const scoringType=this.shotLog[this.ball.shotId]?.type;this.score[t]++;this.goalCelebration=this.goalCelebrant===this.careerIndex?this.careerLook?.celebration??0:((this.goalCelebrant??0)+this.score[t])%3;if(this.ball.owner!==null)this.lastStriker=this.ball.owner;if(this.lastStriker!==null&&this.players[this.lastStriker].t===t){if(this.ball.kind!=='shot'){this.shots[t]++;this.stats[this.lastStriker].shots++}this.stats[this.lastStriker].goals++;if(scoringType==='header')this.stats[this.lastStriker].headerGoals++;if(scoringType==='bicycle')this.stats[this.lastStriker].bicycleGoals++;if(scoringType==='penalty')this.stats[this.lastStriker].penaltyGoals++;this.stats[this.lastStriker].shotsOnTarget++;this.onTarget[t]++;if(this.lastPasser!==null&&this.lastPasser!==this.lastStriker&&this.players[this.lastPasser].t===t)this.stats[this.lastPasser].assists++}if(!this.practice)freezeGoal(this,t);const label=`${this.teams[t]}进球！`;this.lastStriker=null;this.lastPasser=null;if(!this.practice)this.reset(1-t);this.announce(label,this.practice?0:2.4)}
  aiMove(id,holder,pressure){
    const p=this.players[id],d=this.direction(p.t),b=this.ball,level=this.aiLevel(p.t),gx=d===1?FIELD.right:FIELD.left,plan=this.teamPlan(p.t);
    if(p.stationary)return [0,0];
    if(p.i===0){const [x,y]=this.keeperTarget(p,b);return [x-p.x,y-p.y]}
    if(p.aiKick){if(b.owner!==id)p.aiKick=null;else if(this.time>=p.aiKick.at){const action=p.aiKick;p.aiKick=null;this.kick(id,action.shoot,action.power,action.target,action.lead);return [0,0]}else return [0,0]}
    if(b.owner===id){
      const rivals=this.players.filter((q,j)=>q.t!==p.t&&q.i!==0&&this.active(j)),near=rivals.filter(q=>distance(p,q)<100),danger=near.some(q=>(q.x-p.x)*d>-18&&Math.abs(q.y-p.y)<55)||near.some(q=>distance(p,q)<55);
      const outlet=this.passOption(id,null,true,true),opening=this.kickoffId===id;
      if(p.cool===0&&p.decisionCool<=0){
        p.decisionCool=[.32,.22,.16,.12][level];
        if(opening&&outlet){return this.queueAiKick(id,false,.4,outlet.j,true)}
        const returnRun=this.giveGo;if(returnRun?.receiver===id&&returnRun.until>this.time&&level>=1&&plan.mentality!=='protect'){const back=this.passOption(id,returnRun.id,true);if(back&&back.progress>25&&back.lane>28){this.giveGo=null;return this.queueAiKick(id,false,.4,back.j,true)}}
        const shot=this.shotTarget(id);if(shot){return this.queueAiKick(id,true,.45+level*.16,shot)}
        if(outlet&&((plan.style==='balanced'||plan.mentality==='protect')&&this.time-(p.heldSince??0)>2.2&&p.settle===0&&distance(p,outlet.q)<230&&outlet.progress>15&&outlet.lane>30||plan.style==='counter'&&this.time-this.attackStarted[p.t]<4&&outlet.progress>70||danger&&(outlet.progress>-30||near.some(q=>distance(p,q)<55))||Math.abs(gx-p.x)<240&&!this.shotOpen(id)&&outlet.progress>25||distance(p,outlet.q)<200&&outlet.progress>65)){return this.queueAiKick(id,false,.4,outlet.j,true)}
      }
      if(danger&&p.avoidTime<=0){const upper=near.reduce((n,q)=>n+1/(20+Math.hypot(q.x-(p.x+d*55),q.y-(p.y-65))),0),lower=near.reduce((n,q)=>n+1/(20+Math.hypot(q.x-(p.x+d*55),q.y-(p.y+65))),0);p.avoidSide=upper<lower?-1:1;if(p.y<FIELD.top+80)p.avoidSide=1;if(p.y>FIELD.bottom-80)p.avoidSide=-1;p.avoidTime=.55}
      return [clamp(gx-d*38-p.x,-140,140)*(danger?.6:1),p.avoidTime>0?p.avoidSide*85:(FIELD.center+(p.hy-.5)*65-p.y)*(Math.abs(gx-p.x)<260?1:.5)];
    }
    if(b.owner===null&&b.last===p.t&&b.receiver===id&&b.receivePoint)return [b.receivePoint.x-p.x,b.receivePoint.y-p.y];
    if(b.owner===null){const landing=Math.max(0,(b.vz+Math.sqrt(b.vz*b.vz+630*b.z))/315),look=b.z>8?Math.min(.65,landing):.18,point={x:clamp(b.x+b.vx*look*.8,FIELD.left+12,FIELD.right-12),y:clamp(b.y+b.vy*look*.8,FIELD.top+12,FIELD.bottom-12)},chaser=pressure[p.t].slice().sort((a,c)=>distance(a.p,point)-distance(c.p,point))[0];if(chaser?.id===id||pressure[p.t][1]?.id===id&&b.kind!=='parry')return [point.x-p.x,point.y-p.y];if(b.kind==='parry'&&p.i>2)return [clamp(point.x-d*65,FIELD.left+20,FIELD.right-20)-p.x,clamp(point.y+(p.hy<.5?-70:70),FIELD.top+20,FIELD.bottom-20)-p.y]}
    if(holder&&holder.t!==p.t&&pressure[p.t].slice(0,this.pressers(p.t)).some(a=>a.id===id)){const order=pressure[p.t].findIndex(a=>a.id===id);if(order===0||level<2)return [b.x+holder.vx*.12-p.x,b.y+holder.vy*.12-p.y];if(order===1)return [holder.x-d*55-p.x,holder.y+(FIELD.center-holder.y)*.18-p.y];const goal=d===1?FIELD.left:FIELD.right,targets=this.players.filter((q,j)=>q.t===holder.t&&q.i!==0&&q!==holder&&this.active(j)).sort((a,c)=>Math.abs(a.x-goal)-Math.abs(c.x-goal));const target=targets[(order-2)%targets.length];return target?[target.x-d*24-p.x,target.y+(FIELD.center-target.y)*.12-p.y]:[b.x-d*35-p.x,b.y-p.y]}
    if(this.giveGo?.id===id&&this.giveGo.until>this.time&&holder?.t===p.t&&plan.mentality!=='protect')return [this.giveGo.x-p.x,this.giveGo.y-p.y];
    let tx=FIELD.left+(d===1?p.hx:1-p.hx)*FIELD.width+(b.x-FIELD.mid)*.30+d*plan.line,ty=FIELD.top+p.hy*FIELD.height+(b.y-FIELD.center)*.18;
    if(holder?.t===p.t&&holder.i!==0){
      const support=this.players.map((q,j)=>({q,j})).filter(({q,j})=>q.t===p.t&&q.i!==0&&j!==b.owner&&this.active(j)).sort((a,c)=>distance(a.q,holder)-distance(c.q,holder))[0];
      if(support?.j===id){tx=holder.x-d*85;ty=holder.y+(p.hy<.5?-1:p.hy>.5?1:holder.y<FIELD.center?1:-1)*85}
      else if(p.i>2){tx=holder.x+d*((plan.style==='counter'?165:plan.style==='press'?140:125)+plan.forward);ty=FIELD.center+(p.hy-.5)*(Math.abs(gx-holder.x)<240?280:540);if(Math.abs(gx-holder.x)<240){tx=gx-d*(p.i===5?65:p.hy<.5?125:195);ty=FIELD.center+(p.i===5?Math.sign(FIELD.center-holder.y)*32:(p.hy<.5?-80:80))}}
      else tx+=d*35;
    }else if(holder&&holder.t!==p.t&&level>=2&&Math.abs(holder.x-(d===1?FIELD.left:FIELD.right))<380){const goal=d===1?FIELD.left:FIELD.right,threat=this.players.filter((q,j)=>q.t!==p.t&&q.i!==0&&q!==holder&&this.active(j)&&Math.abs(q.x-goal)<Math.abs(holder.x-goal)+100&&((p.hy<.5&&q.y<FIELD.center)||(p.hy>.5&&q.y>=FIELD.center)||p.i===5)).sort((a,c)=>Math.abs(a.x-goal)-Math.abs(c.x-goal))[0];tx=holder.x-d*(p.i<=2?115:85);ty=FIELD.center+(holder.y-FIELD.center)*.45+(p.hy-.5)*190;if(threat){tx=threat.x-d*35;ty=threat.y+(FIELD.center-threat.y)*.12}tx+=d*plan.line*.4;tx=clamp(tx,Math.min(goal+d*45,holder.x-d*25),Math.max(goal+d*45,holder.x-d*25))}
    return [clamp(tx,FIELD.left+20,FIELD.right-20)-p.x,clamp(ty,FIELD.top+20,FIELD.bottom-20)-p.y];
  }
  step(dt,inputs=[{},{}]){if(this.state!=='playing')return;dt=clamp(dt,0,.04);if(dt>.016){const count=Math.ceil(dt/.016);for(let i=0;i<count;i++)this.step(dt/count,inputs);return}this.noticeTime=Math.max(0,this.noticeTime-dt);this.shotFeedbackTime=Math.max(0,(this.shotFeedbackTime??0)-dt);if(this.pendingShot){this.pendingShot.left-=dt;if(this.pendingShot.left<=0)this.pendingShot=null}if(this.wait>0){this.wait-=dt;return}recordFrame(this);if(!this.shootoutMode)this.time+=dt;this.players.forEach((p,id)=>{if(this.active(id))this.stats[id].playingSeconds+=dt});if(!this.shootoutMode&&this.time>=this.duration){this.resolveShot('whistle');this.state='ended';this.announce('全场结束',0);return}if(!this.shootoutMode&&this.half===1&&this.time>=this.duration/2){this.resolveShot('whistle');this.half=2;this.players.forEach(p=>p.stamina=clamp(p.stamina+.35,0,1));this.reset(1);this.announce('下半场 · 交换场地',2);return}if(this.setPiece){const {id,at}=this.setPiece,input=inputs[0]??{};if(this.ball.owner!==id||input.x||input.y||input.shoot)this.setPiece=null;else if(this.time-at>.8){const p=this.players[id],outlet=this.passOption(id,null,true,true);if(outlet)this.kick(id,false,.4,outlet.j,true);else{const x=clamp(p.x-this.direction(0)*105,FIELD.left+60,FIELD.right-60),y=FIELD.center,n=Math.hypot(x-p.x,y-p.y)||1;this.release(id,(x-p.x)/n*350,(y-p.y)/n*350,0,'pass');this.passes[0]++;this.stats[id].passes++}this.setPiece=null}}
    this.ball.keeperDelay=Math.max(0,(this.ball.keeperDelay??0)-dt);this.ball.lock=Math.max(0,this.ball.lock-dt);this.kickoffGrace=Math.max(0,this.kickoffGrace-dt);const holder=this.ball.owner===null?null:this.players[this.ball.owner];this.heatClock+=dt;if(!this.shootoutMode&&this.heatClock>=.25){this.heatClock-=.25;this.players.forEach((p,id)=>{if(!this.active(id))return;const nx=this.direction(p.t)===1?(p.x-FIELD.left)/FIELD.width:(FIELD.right-p.x)/FIELD.width,ny=(p.y-FIELD.top)/FIELD.height,cell=clamp(Math.floor(nx*12),0,11)+clamp(Math.floor(ny*8),0,7)*12,half=(this.half-1)*2;this.heat[id][half][cell]+=.25;if(this.ball.owner===id)this.heat[id][half+1][cell]+=.25})}if(holder){this.possession[holder.t]+=dt;this.stats[this.ball.owner].possession+=dt}
    if(inputs[0]?.shoot&&this.ball.owner===this.selected[0])this.charge=Math.min(1,this.charge+dt/.65)
    if(this.shootoutMode&&this.ball.owner===null){this.shotElapsed+=dt;if(this.shotElapsed>3||this.ball.x<FIELD.left||this.ball.x>FIELD.right||this.ball.y<FIELD.top||this.ball.y>FIELD.bottom){const b=this.ball;this.shotOutcome=(b.x<FIELD.left||b.x>FIELD.right)&&b.y>FIELD.center-FIELD.goalHalf&&b.y<FIELD.center+FIELD.goalHalf&&b.z<27;this.state='ended';return}}if(this.penalty){const id=this.ball.owner;if(id!==null&&((this.penalty.team===1)||(this.careerIndex!==null&&this.penalty.team===0&&this.selected[0]!==id))){const p=this.players[id];p.dy=p.i%2?-.4:.4;this.kick(id,true,.8)}return}
    const pressure=[0,1].map(t=>this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)&&!(t===0&&this.selected[0]===id)).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball)));
    this.players.forEach((p,id)=>{if(!this.active(id)||this.shootoutMode&&p.i!==0)return;p.cool=Math.max(0,p.cool-dt);p.decisionCool=Math.max(0,(p.decisionCool??0)-dt);p.avoidTime=Math.max(0,(p.avoidTime??0)-dt);p.settle=Math.max(0,(p.settle??0)-dt);p.tackleRecovery=Math.max(0,(p.tackleRecovery??0)-dt);if(p.dive>0&&p.dive<=dt)p.cool=Math.max(p.cool,.35);p.dive=Math.max(0,(p.dive??0)-dt);p.tackleWindup=Math.max(0,(p.tackleWindup??0)-dt);const human=p.t===0&&this.selected[0]===id,input=inputs[p.t]||{};let dx=0,dy=0,level=this.aiLevel(p.t);if(human){dx=input.x||0;dy=input.y||0}else{[dx,dy]=this.aiMove(id,holder,pressure);if(Math.hypot(dx,dy)<3){dx=0;dy=0}}
      if(!human&&p.i!==0&&this.ball.owner!==id){for(const q of this.players){if(q!==p&&q.t===p.t&&distance(p,q)<28){dx+=(p.x-q.x)*2;dy+=(p.y-q.y)*2}}}const n=Math.hypot(dx,dy);p.vx=0;p.vy=0;if(n){dx/=n;dy/=n;p.dx=dx;p.dy=dy;p.sprinting=human?!!input.sprint&&p.stamina>.04:p.i!==0&&p.stamina>.18&&((holder?.t!==p.t&&pressure[p.t][0]?.id===id&&distance(p,this.ball)>65&&distance(p,this.ball)<230)||(holder?.t===p.t&&p.i>2&&this.teamPlan(p.t).style==='counter'&&this.time-this.attackStarted[p.t]<2.5&&distance(p,holder)<190));const speed=(human?120:(p.i===0?(p.dive>0?215:145):(p.t===0?(this.tactic==='press'?107:this.tactic==='counter'&&this.ball.owner===id?112:100):[100,103,106,109][this.difficulty])*this.strength[p.t]))*(p.sprinting?(human?(['runner','engine'].includes(this.careerStyle)?1.52:this.careerStyle==='creator'?1.42:1.48):1.18):this.careerStyle==='finisher'&&human?.97:1)*(this.ball.owner===id?.91:1)*(p.tackleRecovery>0?.65:1)*(.8+.2*clamp(p.stamina/.25,0,1))*(p.i===0?1:.97)*(p.sprinting?.99:1)*(1+(this.skill(id,'speed')-60)*.006);p.vx=dx*speed;p.vy=dy*speed;if(this.kickoffId===id)this.kickoffId=null;p.x=clamp(p.x+dx*speed*dt,FIELD.left+4,FIELD.right-4);p.y=clamp(p.y+dy*speed*dt,FIELD.top+4,FIELD.bottom-4);this.stats[id].distance+=speed*dt/10;if(this.ball.owner===id)this.stats[id].carryDistance+=speed*dt/10;p.anim+=dt*speed/10;p.stamina=clamp(p.stamina+(p.sprinting?(human&&['runner','engine'].includes(this.careerStyle)?-.24:-.3):.15)*dt,0,1)}else{p.sprinting=false;p.stamina=clamp(p.stamina+.18*dt,0,1)}
      if(!human&&p.tackleTarget!==null&&p.tackleWindup===0){const target=p.tackleTarget;p.tackleTarget=null;if(this.ball.owner===target)this.attemptTackle(id,true);else p.cool=Math.max(p.cool,.18)}
      if(!human&&this.kickoffGrace===0&&p.cool===0&&p.tackleTarget===null&&this.ball.owner!==null&&this.players[this.ball.owner].t!==p.t&&distance(p,this.ball)<35){p.tackleTarget=this.ball.owner;p.tackleWindup=[.20,.15,.11,.08][level]}
      if(!human&&this.ball.owner===null&&this.ball.z>8&&this.ball.z<31&&distance(p,this.ball)<20&&Math.abs((this.direction(p.t)===1?FIELD.right:FIELD.left)-p.x)<240)this.aerial(id);
      if(!this.shootoutMode&&this.ball.owner===id&&p.i===0&&p.cool===0)this.kick(id);
    });
    const b=this.ball;if(b.owner!==null){const p=this.players[b.owner];b.x=p.x+p.dx*11;b.y=p.y+p.dy*11;b.z=0}else{b.x+=b.vx*dt;b.y+=b.vy*dt;b.z=Math.max(0,b.z+b.vz*dt);if(b.z)b.vz-=315*dt;else if(b.vz<0)b.vz=0;const drag=Math.exp(-.58*dt);b.vx*=drag;b.vy*=drag;const catcher=this.players.findIndex((p,id)=>this.active(id)&&(p.cool===0||p.i===0)&&(b.lock<=0||p.t!==this.players[this.lastStriker]?.t)&&this.canCollect(p,b));if(catcher!==-1){const keeper=this.players[catcher],parried=keeper.i===0&&b.kind==='shot'&&b.last!==keeper.t&&(keeper.dive>0||Math.hypot(b.vx,b.vy)>660)&&Math.abs(b.y-keeper.y)>8&&this.parry(catcher);if(!parried)this.takeBall(catcher);if(this.shootoutMode){this.shotOutcome=false;this.state='ended';return}}}
    if(this.pendingShot&&this.ball.owner===this.pendingShot.id&&this.selected[0]===this.pendingShot.id){const shot=this.pendingShot;this.pendingShot=null;this.kick(shot.id,true,shot.power,shot.target)}
    const side=b.x<FIELD.left?-1:b.x>FIELD.right?1:0;if(this.shootoutMode){if(side||b.y<FIELD.top||b.y>FIELD.bottom){this.shotOutcome=!!side&&b.y>FIELD.center-FIELD.goalHalf&&b.y<FIELD.center+FIELD.goalHalf&&b.z<27;this.state='ended'}return}if(side){if(!(b.y>FIELD.center-FIELD.goalHalf&&b.y<FIELD.center+FIELD.goalHalf&&b.z<27))this.resolveShot('wide');if(b.y>FIELD.center-FIELD.goalHalf&&b.y<FIELD.center+FIELD.goalHalf&&b.z<27)this.goal(this.direction(0)===side?0:1);else{const defender=this.direction(0)===-side?0:1;if(b.last===defender)this.restart(1-defender,side<0?FIELD.left+8:FIELD.right-8,b.y<FIELD.center?FIELD.top+8:FIELD.bottom-8,'角球');else this.restart(defender,side<0?FIELD.left+65:FIELD.right-65,FIELD.center,'球门球')}}else if(b.y<FIELD.top||b.y>FIELD.bottom){this.resolveShot('wide');this.restart(1-b.last,clamp(b.x,FIELD.left+20,FIELD.right-20),b.y<FIELD.top?FIELD.top+7:FIELD.bottom-7,'边线球')}
  }
}
