export const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
export const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
export const FIELD = {left: 40, right: 920, top: 40, bottom: 540, mid: 480, center: 290};
const formation = [[.035,.5],[.23,.28],[.23,.72],[.38,.25],[.38,.75],[.38,.5]];

export class Match {
  constructor({difficulty=1, duo=false, duration=180, teams=['蓝湾 FC','赤焰联队'], strength=[1,1], tactic='balanced'}={}) {
    Object.assign(this,{difficulty,duo,duration,teams,strength,tactic});
    // ponytail: fixed foul cadence keeps refereeing predictable; replace with contact physics if fouls become a main mechanic.
    this.time=0; this.half=1; this.score=[0,0]; this.shots=[0,0]; this.passes=[0,0]; this.crosses=[0,0]; this.fouls=[0,0]; this.tackles=[0,0]; this.possession=[0,0];
    this.stats=Array.from({length:12},()=>({goals:0,assists:0,shots:0,headers:0,bicycles:0,yellows:0,reds:0}));
    this.players=[];this.selected=[5,11];this.state='ready';this.event='准备开球';this.eventId=0;this.wait=0;this.charge=[0,0];this.penalty=null;this.lastPasser=null;this.lastStriker=null;this.reset(0);
  }
  direction(t){return (t===0?1:-1)*(this.half===1?1:-1)}
  active(id){return !this.stats[id].reds}
  announce(s,wait=1.3){this.event=s;this.eventId++;this.wait=wait}
  available(t){return [5,4,3,2,1].map(i=>t*6+i).find(id=>this.active(id))}
  pressers(t){return t===0?(this.tactic==='press'?3:this.tactic==='counter'?1:2):this.difficulty+1}
  reset(t){const f=FIELD;this.players=[];for(let side=0;side<2;side++)formation.forEach(([fx,fy],i)=>{let d=this.direction(side);this.players.push({x:f.left+(d===1?fx:1-fx)*(f.right-f.left),y:f.top+fy*(f.bottom-f.top),hx:fx,hy:fy,t:side,i,dx:d,dy:0,stamina:1,cool:0,anim:0,sprinting:false})});const id=this.available(t);this.players[id].x=f.mid-this.direction(t)*10;this.players[id].y=f.center;this.ball={x:f.mid,y:f.center,z:0,vx:0,vy:0,vz:0,owner:id,lock:0,last:t};this.selected=[this.available(0),this.available(1)];this.selected[t]=id;this.charge=[0,0];this.penalty=null;this.kickoffGrace=3.5}
  switch(t){const pool=this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball));this.selected[t]=pool[0].id===this.selected[t]&&pool[1]?pool[1].id:pool[0].id}
  release(id,vx,vy,vz=0,kind='pass'){const p=this.players[id],n=Math.hypot(vx,vy)||1;this.ball={x:p.x+vx/n*16,y:p.y+vy/n*16,z:vz?5:0,vx,vy,vz,owner:null,lock:.2,last:p.t};this.lastStriker=id;this.kickoffGrace=0;p.cool=.65;this.charge[p.t]=0;if(kind!=='shot')this.lastPasser=id;if(this.penalty)this.penalty=null}
  kick(id,shoot=false,power=.4){const p=this.players[id];if(this.ball.owner!==id||!this.active(id))return false;const d=this.direction(p.t);let dx=p.dx,dy=p.dy;if(!shoot&&!this.penalty){const pool=this.players.map((q,j)=>({q,j})).filter(({q,j})=>q.t===p.t&&j!==id&&q.i!==0&&this.active(j));pool.sort((a,b)=>(distance(p,a.q)-d*(a.q.x-p.x)*1.2)-(distance(p,b.q)-d*(b.q.x-p.x)*1.2));if(pool[0]){dx=pool[0].q.x-p.x;dy=pool[0].q.y-p.y;this.selected[p.t]=pool[0].j}this.passes[p.t]++}else{shoot=true;this.shots[p.t]++;this.stats[id].shots++;const gx=d===1?FIELD.right:FIELD.left;if(this.penalty){dx=gx-p.x;dy=FIELD.center+(p.dy<-.2?-33:p.dy>.2?33:p.i%2?31:-31)-p.y}else if(dx*d>0&&Math.abs(dy)<.25){dx=gx-p.x;dy=FIELD.center+(p.y<FIELD.center?-28:28)-p.y}}const n=Math.hypot(dx,dy)||1,speed=shoot?410+clamp(power,0,1)*340:360;this.release(id,dx/n*speed,dy/n*speed,0,shoot?'shot':'pass');return true}
  cross(id){const p=this.players[id];if(this.ball.owner!==id||this.penalty||!this.active(id))return false;const d=this.direction(p.t),pool=this.players.map((q,j)=>({q,j})).filter(({q,j})=>q.t===p.t&&j!==id&&q.i!==0&&this.active(j)&&(q.x-p.x)*d>25).sort((a,b)=>Math.abs(a.q.y-FIELD.center)-Math.abs(b.q.y-FIELD.center));const q=pool[0]?.q??{x:clamp(p.x+d*220,FIELD.left+30,FIELD.right-30),y:FIELD.center};const dx=q.x-p.x,dy=q.y-p.y,n=Math.hypot(dx,dy)||1,speed=clamp(n/.82,165,520);if(pool[0])this.selected[p.t]=pool[0].j;this.crosses[p.t]++;this.passes[p.t]++;this.release(id,dx/n*speed,dy/n*speed,130,'cross');return true}
  aerial(id,bicycle=false){const p=this.players[id],b=this.ball;if(!this.active(id)||b.owner!==null||b.z<9||b.z>37||distance(p,b)>25)return false;const gx=this.direction(p.t)===1?FIELD.right:FIELD.left,gy=FIELD.center+(p.y<FIELD.center?-23:23),dx=gx-p.x,dy=gy-p.y,n=Math.hypot(dx,dy),speed=bicycle?760:620;this.shots[p.t]++;this.stats[id].shots++;this.stats[id][bicycle?'bicycles':'headers']++;b.vx=dx/n*speed;b.vy=dy/n*speed;b.vz=bicycle?25:4;b.lock=.18;b.last=p.t;this.lastStriker=id;this.kickoffGrace=0;p.cool=.65;p.anim+=12;this.announce(bicycle?'倒钩射门！':'头球攻门！',.35);return true}
  takeBall(id){const former=this.ball.owner;if(former!==null&&former!==id)this.players[former].cool=.6;this.ball.owner=id;this.ball.z=0;this.ball.vz=0;this.ball.last=this.players[id].t;this.players[id].cool=.35;if(former!==null&&this.players[former].t!==this.players[id].t)this.lastPasser=null}
  restart(t,x,y,label,wait=1.1){const pool=this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)).sort((a,b)=>distance(a.p,{x,y})-distance(b.p,{x,y}));const id=pool[0].id;this.players[id].x=x-this.direction(t)*10;this.players[id].y=y;this.ball={x,y,z:0,vx:0,vy:0,vz:0,owner:id,lock:0,last:t};this.selected[t]=id;this.lastPasser=null;this.announce(label,wait)}
  foul(id,victim){const p=this.players[id];this.fouls[p.t]++;this.stats[id].yellows++;const red=this.stats[id].yellows>=2;if(red){this.stats[id].reds=1;this.selected[p.t]=this.available(p.t)}const gx=this.direction(p.t)===1?FIELD.left:FIELD.right;const penalty=Math.abs(p.x-gx)<145&&Math.abs(p.y-FIELD.center)<125,t=this.players[victim].t;if(penalty){this.restart(t,gx===FIELD.left?FIELD.left+120:FIELD.right-120,FIELD.center,`点球！${red?'红牌':'黄牌'}`,1.5);this.penalty={team:t}}else this.restart(t,clamp(p.x,FIELD.left+20,FIELD.right-20),clamp(p.y,FIELD.top+20,FIELD.bottom-20),`犯规 · ${red?'红牌':'黄牌'}`,1.2)}
  tackle(t){const id=this.selected[t],p=this.players[id];if(!p||!this.active(id)||p.cool>0||this.penalty)return;const holder=this.ball.owner;if(holder!==null&&this.players[holder].t!==t&&distance(p,this.players[holder])<31){const q=this.players[holder],behind=(p.x-q.x)*q.dx+(p.y-q.y)*q.dy<-12;if(behind)this.foul(id,holder);else this.takeBall(id)}p.cool=.65}
  goal(t){this.score[t]++;if(this.lastStriker!==null&&this.players[this.lastStriker].t===t){this.stats[this.lastStriker].goals++;if(this.lastPasser!==null&&this.lastPasser!==this.lastStriker&&this.players[this.lastPasser].t===t)this.stats[this.lastPasser].assists++}const label=`${this.teams[t]}进球！`;this.lastStriker=null;this.lastPasser=null;this.reset(1-t);this.announce(label,2.4)}
  step(dt,inputs=[{},{}]){if(this.state!=='playing')return;dt=clamp(dt,0,.04);if(this.wait>0){this.wait-=dt;return}this.time+=dt;if(this.time>=this.duration){this.state='ended';this.announce('全场结束',0);return}if(this.half===1&&this.time>=this.duration/2){this.half=2;this.reset(1);this.announce('下半场 · 交换场地',2);return}this.ball.lock=Math.max(0,this.ball.lock-dt);this.kickoffGrace=Math.max(0,this.kickoffGrace-dt);const holder=this.ball.owner===null?null:this.players[this.ball.owner];if(holder)this.possession[holder.t]+=dt;
    if(this.penalty){const id=this.ball.owner;if(id!==null&&this.penalty.team===1&&!this.duo){const p=this.players[id];p.dy=p.i%2?-.4:.4;this.kick(id,true,.8)}return}
    const pressure=[0,1].map(t=>this.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&this.active(id)&&!((t===0||this.duo)&&this.selected[t]===id)).sort((a,b)=>distance(a.p,this.ball)-distance(b.p,this.ball)));
    this.players.forEach((p,id)=>{if(!this.active(id))return;p.cool=Math.max(0,p.cool-dt);const human=(p.t===0||this.duo)&&this.selected[p.t]===id,input=inputs[p.t]||{};let dx=0,dy=0;if(human){dx=input.x||0;dy=input.y||0;if(input.shoot&&this.ball.owner===id)this.charge[p.t]=Math.min(1,this.charge[p.t]+dt*1.25)}else{const d=this.direction(p.t),b=this.ball;let tx=p.x,ty=p.y;if(p.i===0){tx=d===1?FIELD.left+29:FIELD.right-29;ty=clamp(b.y,FIELD.center-44,FIELD.center+44);if(Math.abs(b.x-tx)<115){tx=clamp(b.x,d===1?FIELD.left+12:FIELD.right-88,d===1?FIELD.left+88:FIELD.right-12);ty=clamp(b.y,FIELD.center-75,FIELD.center+75)}}else if(this.ball.owner===id){const gx=d===1?FIELD.right:FIELD.left;tx=gx-d*38;ty=FIELD.center+(p.hy-.5)*65;if(Math.abs(gx-p.x)<[205,260,310][this.difficulty]*this.strength[p.t]&&p.cool===0){p.dx=d;p.dy=(FIELD.center+(p.i%2?30:-30)-p.y)/250;this.kick(id,true,.45+this.difficulty*.16)}else if(p.cool===0&&pressure[1-p.t]?.some(({p:q})=>distance(q,p)<29)&&this.players.some((q,j)=>q.t===p.t&&this.active(j)&&(q.x-p.x)*d>70&&distance(q,p)<260)&&this.difficulty>0)this.kick(id)}else if((!holder||holder.t!==p.t)&&pressure[p.t].slice(0,this.pressers(p.t)).some(a=>a.id===id)){tx=b.x+b.vx*.1;ty=b.y+b.vy*.1}else{tx=FIELD.left+(d===1?p.hx:1-p.hx)*(FIELD.right-FIELD.left)+(b.x-FIELD.mid)*.30+(holder?.t===p.t?d*65:0);ty=FIELD.top+p.hy*(FIELD.bottom-FIELD.top)+(b.y-FIELD.center)*.18}dx=tx-p.x;dy=ty-p.y;if(Math.hypot(dx,dy)<3){dx=0;dy=0}}
      const n=Math.hypot(dx,dy);if(n){dx/=n;dy/=n;p.dx=dx;p.dy=dy;p.sprinting=human&&!!input.sprint&&p.stamina>.04;const speed=(human?120:(p.i===0?155:(p.t===0?(this.tactic==='press'?107:this.tactic==='counter'&&this.ball.owner===id?112:100):[88,103,110][this.difficulty])*this.strength[p.t]))*(p.sprinting?1.48:1)*(this.ball.owner===id?.91:1);p.x=clamp(p.x+dx*speed*dt,FIELD.left+4,FIELD.right-4);p.y=clamp(p.y+dy*speed*dt,FIELD.top+4,FIELD.bottom-4);p.anim+=dt*speed/10;p.stamina=clamp(p.stamina+(p.sprinting?-.3:.15)*dt,0,1)}else{p.sprinting=false;p.stamina=clamp(p.stamina+.18*dt,0,1)}
      if(!human&&this.kickoffGrace===0&&p.cool===0&&this.ball.owner!==null&&this.players[this.ball.owner].t!==p.t&&distance(p,this.ball)<[18,23,27][this.difficulty]){const holderId=this.ball.owner;this.tackles[p.t]++;if(p.i!==0&&this.tackles[p.t]%8===0)this.foul(id,holderId);else this.takeBall(id)}
      if(!human&&this.ball.owner===null&&this.ball.z>8&&this.ball.z<31&&distance(p,this.ball)<20&&Math.abs((this.direction(p.t)===1?FIELD.right:FIELD.left)-p.x)<240)this.aerial(id);
      if(this.ball.owner===id&&p.i===0&&p.cool===0)this.kick(id);
    });
    const b=this.ball;if(b.owner!==null){const p=this.players[b.owner];b.x=p.x+p.dx*11;b.y=p.y+p.dy*11;b.z=0}else{b.x+=b.vx*dt;b.y+=b.vy*dt;b.z=Math.max(0,b.z+b.vz*dt);if(b.z)b.vz-=315*dt;else if(b.vz<0)b.vz=0;const drag=Math.exp(-.58*dt);b.vx*=drag;b.vy*=drag;if(b.z<9){const catcher=this.players.findIndex((p,id)=>this.active(id)&&p.cool===0&&(b.lock<=0||p.t!==this.players[this.lastStriker]?.t)&&distance(p,b)<(p.i===0?18:12));if(catcher!==-1)this.takeBall(catcher)}}
    const side=b.x<FIELD.left?-1:b.x>FIELD.right?1:0;if(side){if(b.y>242&&b.y<338&&b.z<27)this.goal(this.direction(0)===side?0:1);else{const defender=this.direction(0)===-side?0:1;if(b.last===defender)this.restart(1-defender,side<0?FIELD.left+8:FIELD.right-8,b.y<FIELD.center?FIELD.top+8:FIELD.bottom-8,'角球');else this.restart(defender,side<0?FIELD.left+65:FIELD.right-65,FIELD.center,'球门球')}}else if(b.y<FIELD.top||b.y>FIELD.bottom)this.restart(1-b.last,clamp(b.x,FIELD.left+20,FIELD.right-20),b.y<FIELD.top?FIELD.top+7:FIELD.bottom-7,'边线球');
  }
}
