import assert from 'node:assert/strict';
import {createSeason,prepareSeason,standings,playerRows} from './league.mjs';
import {createCareerPlayer} from './career.mjs';
import {editPlayer,editPlayerStats,editTeamName} from './god-mode.mjs';
import {teamName,activePlayers,rosterRating} from './identity.mjs';
import {Match} from './engine.mjs';
import {makeClubSlot,makeCareerSlot,exportBackup,importBackup} from './save-slots.mjs';

let season=createSeason('england','arsenal',5),id=season.rosterIds.arsenal[5];
assert.throws(()=>editTeamName(season,'arsenal','新名字'));
season.godMode=true;
season=editTeamName(season,'arsenal','像素枪手');
assert.equal(teamName(season,'arsenal'),'像素枪手');
assert.equal(standings(season)[0].name,'像素枪手');
const rating=rosterRating(season,'arsenal');
let result=editPlayer(season,null,id,{name:'决胜者',number:42,attributes:{shooting:99}});
season=result.season;
assert.equal(season.playerData[id].name,'决胜者');
assert.equal(activePlayers(season,'arsenal')[5].number,42);
assert(rosterRating(season,'arsenal')>rating);
assert.throws(()=>editPlayer(season,null,id,{number:6}));
const opponent=season.rosterIds.chelsea[5];
season=editPlayer(season,null,id,{teamId:'chelsea',position:5}).season;
assert.equal(season.rosterIds.chelsea[5],id);
assert.equal(season.rosterIds.arsenal[5],opponent);
assert.equal(season.playerData[opponent].teamId,'arsenal');
season=editPlayerStats(season,null,id,'league','england',{goals:4,shots:9}).season;
assert.equal(playerRows(season).find(p=>p.id===id).goals,4);
assert.equal(season.world.england,undefined);
const barcelona=season.rosterIds.barcelona[5];
season=editPlayer(season,null,id,{teamId:'barcelona',position:5}).season;
assert.equal(season.rosterIds.barcelona[5],id);
assert.equal(season.world.spain.players[id].goals,4);
assert.equal(season.players[id],undefined);
assert.equal(season.playerData[barcelona].teamId,'chelsea');
const numbers=[...activePlayers(season,'chelsea'),...activePlayers(season,'arsenal')].map(p=>p.number);
const match=new Match({playerNumbers:numbers,playerIds:[...season.rosterIds.chelsea,...season.rosterIds.arsenal]});
assert.deepEqual(match.report().numbers,numbers);
let backup=importBackup(exportBackup({version:2,active:0,slots:[makeClubSlot(season),null,null]}));
assert.equal(backup.slots[0].season.playerData[id].number,42);
assert.equal(backup.slots[0].season.teamNames.arsenal,'像素枪手');
const broken=structuredClone(backup);broken.slots[0].season.playerData[id].number=broken.slots[0].season.playerData[broken.slots[0].season.rosterIds.barcelona[1]].number;
assert.throws(()=>importBackup(JSON.stringify(broken)));

const career=createCareerPlayer('新星',10,'forward');let careerSeason=createSeason('england','arsenal',8);prepareSeason(careerSeason,career);careerSeason.godMode=true;
const edited=editPlayer(careerSeason,career,career.id,{name:'传奇',number:27,attributes:{shooting:96}});
assert.equal(edited.career.name,'传奇');assert.equal(edited.career.number,27);assert.equal(edited.career.attributes.shooting,96);
assert.throws(()=>editPlayer(edited.season,edited.career,career.id,{teamId:'chelsea'}));
const stat=editPlayerStats(edited.season,edited.career,career.id,'league','england',{goals:2});
assert.equal(stat.career.stats.goals,2);
backup=importBackup(exportBackup({version:2,active:0,slots:[makeCareerSlot(stat.season,stat.career),null,null]}));
assert.equal(backup.slots[0].player.number,27);
console.log('PASS: God Mode names, numbers, ratings, transfers, stats, MyCareer and backup integrity.');
