import React,{useEffect,useMemo,useState} from 'react';
import {LEAGUES,getTeam} from './league.mjs';
import {teamName} from './identity.mjs';
import {ABILITIES,ABILITY_LABELS,STAT_FIELDS,STAT_LABELS,POSITION_LABELS,overall,teamLeague} from './god-mode.mjs';

const statColumns=['goals','assists','shots','passesCompleted','tackles','saves'];
export function GodModePage({season,career,onToggle,onPlayer,onTeam,onStats,onUndo,canUndo,locked}){
  const [tab,setTab]=useState('players'),[query,setQuery]=useState(''),[league,setLeague]=useState('all'),[sort,setSort]=useState('team'),[descending,setDescending]=useState(false),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[statDraft,setStatDraft]=useState(null),[statScope,setStatScope]=useState('league'),[message,setMessage]=useState('');
  const players=useMemo(()=>Object.values(season?.playerData??{}),[season]);
  const rows=useMemo(()=>players.filter(p=>(league==='all'||teamLeague(p.teamId)===league)&&`${p.name} ${teamName(season,p.teamId)} ${p.id} ${p.number}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const x=sort==='team'?teamName(season,a.teamId):sort==='overall'?overall(a):sort==='number'?a.number:a.name,y=sort==='team'?teamName(season,b.teamId):sort==='overall'?overall(b):sort==='number'?b.number:b.name;return (typeof x==='number'?x-y:String(x).localeCompare(String(y),'zh'))*(descending?-1:1)}),[players,season,league,query,sort,descending]);
  const player=season?.playerData?.[selected];
  useEffect(()=>{if(player){setDraft({name:player.name,number:player.number,teamId:player.teamId,position:player.position,attributes:{...player.attributes}});setStatDraft(null);setStatScope('league')}else setDraft(null)},[selected,player]);
  const statsState=statScope==='cup'?season?.cup:teamLeague(player?.teamId)===season?.leagueId?season:season?.world?.[teamLeague(player?.teamId)];
  useEffect(()=>{if(player)setStatDraft(Object.fromEntries(STAT_FIELDS.map(k=>[k,statsState?.players?.[player.id]?.[k]??0])))},[selected,statScope,season]);
  const submit=(fn,...args)=>{try{fn(...args);setMessage('已保存到当前存档')}catch(error){setMessage(error.message)}};
  const sortBy=key=>{if(sort===key)setDescending(!descending);else{setSort(key);setDescending(false)}};
  if(!season)return <section className="panel god-empty"><h2>世界数据库</h2><p>先建立或打开俱乐部、MyCareer 存档，再编辑该足球世界。</p></section>;
  return <div className="god-page"><div className="god-hero"><div><span>GLOBAL CONTROL / SAVE {season?.history?.length+1}</span><h2>世界数据库</h2><p>一份存档独立保存球队、球员、能力与统计。能力值会参与下一场比赛和其他球队的模拟。</p></div><div className="god-hero-actions"><label><input type="checkbox" checked={!!season.godMode} disabled={locked} onChange={e=>{onToggle(e.target.checked);setMessage(e.target.checked?'God Mode 已开启':'God Mode 已关闭')}}/> GOD MODE</label><button className="subtle" disabled={!canUndo||locked} onClick={()=>submit(onUndo)}>撤销上次修改</button></div></div>{locked&&<p className="god-message">当前比赛尚未结算。终场后可编辑数据库。</p>}{message&&<p className="god-message" role="status">{message}</p>}<nav className="god-tabs" aria-label="数据库板块">{[['players','球员总表'],['teams','球队总表'],['stats','赛季统计'],['history','操作记录']].map(([key,label])=><button key={key} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {tab==='players'&&<><div className="god-filters"><input aria-label="搜索球员" placeholder="搜索球员、球队、号码或 ID" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="筛选联赛" value={league} onChange={e=>setLeague(e.target.value)}><option value="all">全部联赛</option>{LEAGUES.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><span>{rows.length} / {players.length} 名球员</span></div><div className="god-table-wrap"><table className="god-table"><thead><tr><th>ID</th><th><button onClick={()=>sortBy('name')}>球员 ↕</button></th><th><button onClick={()=>sortBy('team')}>球队 ↕</button></th><th>位置</th><th><button onClick={()=>sortBy('number')}>号码 ↕</button></th><th><button onClick={()=>sortBy('overall')}>综评 ↕</button></th>{ABILITIES.map(k=><th key={k}>{ABILITY_LABELS[k]}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id} className={selected===p.id?'selected':''} onClick={()=>setSelected(p.id)}><td className="god-id">{p.id}</td><td><button className="god-name" onClick={()=>setSelected(p.id)}>{p.name}</button>{career?.id===p.id&&<small> · MYCAREER</small>}</td><td>{teamName(season,p.teamId)}</td><td>{POSITION_LABELS[p.position]}</td><td>{p.number}</td><td><b>{overall(p)}</b></td>{ABILITIES.map(k=><td key={k}>{p.attributes[k]}</td>)}</tr>)}</tbody></table></div>{player&&draft&&<section className="god-editor"><div className="god-editor-head"><div><span>PLAYER EDITOR / {player.id}</span><h3>{player.name} <small>#{player.number}</small></h3></div><button className="subtle" onClick={()=>setSelected(null)}>关闭</button></div><div className="god-fields"><label>姓名<input maxLength="40" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>球衣号码<input type="number" min="1" max="99" value={draft.number} onChange={e=>setDraft({...draft,number:e.target.value})}/></label><label>球队<select value={draft.teamId} onChange={e=>setDraft({...draft,teamId:e.target.value})}>{LEAGUES.map(l=><optgroup key={l.id} label={l.name}>{l.teams.map(t=><option key={t.id} value={t.id}>{teamName(season,t.id)}</option>)}</optgroup>)}</select></label><label>场上位置<select value={draft.position} onChange={e=>setDraft({...draft,position:+e.target.value})}>{POSITION_LABELS.map((name,i)=><option key={i} value={i}>{i+1} · {name}</option>)}</select></label>{ABILITIES.map(k=><label key={k}>{ABILITY_LABELS[k]}<input type="number" min="1" max="99" value={draft.attributes[k]} onChange={e=>setDraft({...draft,attributes:{...draft.attributes,[k]:e.target.value}})}/></label>)}</div><p>换队或换位置将与目标位置的球员交换。号码不能与同队球员重复。</p><button className="primary" disabled={!season.godMode||locked} onClick={()=>submit(onPlayer,player.id,draft)}>保存球员</button></section>}</>}
    {tab==='teams'&&<div className="god-team-grid">{LEAGUES.map(l=><section key={l.id} className="god-team-league"><h3>{l.name}</h3>{l.teams.map(t=><TeamEditor key={t.id} team={t} name={teamName(season,t.id)} enabled={season.godMode&&!locked} onSave={name=>submit(onTeam,t.id,name)}/>)}</section>)}</div>}
    {tab==='stats'&&<><p className="god-intro">累计统计按当前赛事保存。修改会更新排行榜与 MyCareer 累计数据；已结束比赛的复盘仍保留当时的原始记录。</p><div className="god-filters"><input aria-label="搜索统计球员" placeholder="搜索球员或球队" value={query} onChange={e=>setQuery(e.target.value)}/><select value={league} onChange={e=>setLeague(e.target.value)}><option value="all">全部联赛</option>{LEAGUES.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select value={statScope} onChange={e=>setStatScope(e.target.value)}><option value="league">联赛</option><option value="cup" disabled={!season.cup}>欧洲冠军杯</option></select></div><div className="god-table-wrap"><table className="god-table"><thead><tr><th>球员</th><th>球队</th>{statColumns.map(k=><th key={k}>{STAT_LABELS[k]}</th>)}</tr></thead><tbody>{rows.map(p=>{const state=statScope==='cup'?season.cup:teamLeague(p.teamId)===season.leagueId?season:season.world?.[teamLeague(p.teamId)],r=state?.players?.[p.id]??{};return <tr key={p.id} onClick={()=>setSelected(p.id)}><td><button className="god-name" onClick={()=>setSelected(p.id)}>{p.name}</button></td><td>{teamName(season,p.teamId)}</td>{statColumns.map(k=><td key={k}>{r[k]??0}</td>)}</tr>})}</tbody></table></div>{player&&statDraft&&<section className="god-editor"><div className="god-editor-head"><div><span>{statScope==='cup'?'EUROPEAN CUP':'LEAGUE'} / {player.id}</span><h3>{player.name} · 累计统计</h3></div><button className="subtle" onClick={()=>setSelected(null)}>关闭</button></div><div className="god-fields">{STAT_FIELDS.map(k=><label key={k}>{STAT_LABELS[k]}<input type="number" min="0" step={['distance','carryDistance','possession','playingSeconds'].includes(k)?'0.01':'1'} value={statDraft[k]} onChange={e=>setStatDraft({...statDraft,[k]:e.target.value})}/></label>)}</div><button className="primary" disabled={!season.godMode||locked} onClick={()=>submit(onStats,player.id,statScope,teamLeague(player.teamId),statDraft)}>保存统计</button></section>}</>}
    {tab==='history'&&<div className="god-history">{[...(season.godEdits??[])].reverse().map((entry,i)=><div key={i}><span>{new Date(entry.at).toLocaleString('zh-CN')}</span><b>{entry.kind}</b><p>{entry.detail}</p></div>)}{!season.godEdits?.length&&<p>尚无 God Mode 修改。</p>}</div>}
  </div>
}

function TeamEditor({team,name,enabled,onSave}){const [draft,setDraft]=useState(name);useEffect(()=>setDraft(name),[name]);return <div className="god-team-row"><span style={{background:team.color}} className="god-team-mark"/><code>{team.id}</code><input aria-label={`${name}名称`} maxLength="60" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="subtle" disabled={!enabled||draft.trim()===name} onClick={()=>onSave(draft)}>保存</button></div>}
