import {LEAGUES,LEGACY_LEAGUES,getLeague,getTeam} from './clubs.mjs';
export {LEAGUES,LEGACY_LEAGUES,getLeague,getTeam};
const surnames=['林','周','陈','江','叶','余','许','沈','陆','宋','何','夏','曹','邱','顾','唐','韩','郑'];
const given=['川','澄','航','野','岚','锐','鸣','辰','越','朗','凯','尧','珂','隽','宁','凡','硕','昕'];
const localNames={
  england:[['Oliver','Mason','Theo','Noah','Elliot','Harry','Jack','Leo'],['Vale','Bennett','Carter','Reed','Walker','Hughes','Ellis','Cole']],
  spain:[['Hugo','Diego','Mateo','Iker','Adrián','Nico','Sergio','Álvaro'],['Aranda','Soler','Vega','Moreno','Ríos','Navarro','Cruz','Molina']],
  germany:[['Lukas','Emil','Jonas','Felix','Leon','Timo','Moritz','Jan'],['Weber','Krüger','Hartmann','Vogel','Keller','Brandt','Neumann','Fischer']],
  italy:[['Luca','Matteo','Marco','Andrea','Enzo','Davide','Nicola','Pietro'],['Rinaldi','Romano','Conti','Ferraro','Costa','Marino','Greco','Moretti']],
  france:[['Hugo','Lucas','Noé','Mathis','Théo','Eliott','Nathan','Maxime'],['Moreau','Laurent','Bernard','Dubois','Roux','Faure','Marchand','Girard']]
};
export function roster(teamId){const league=[...LEAGUES,...LEGACY_LEAGUES].find(l=>l.teams.some(t=>t.id===teamId)),index=league.teams.findIndex(t=>t.id===teamId),names=localNames[league.id];return Array.from({length:6},(_,i)=>names?`${names[0][(index*3+i)%8]} ${names[1][(index*5+i*3)%8]}`:`${surnames[(index*5+i*3)%surnames.length]}${given[(index*7+i*5)%given.length]}`)}
export function fixtures(league){const ids=league.teams.map(t=>t.id),rounds=[];for(let round=0;round<ids.length-1;round++){const games=[];for(let j=0;j<ids.length/2;j++){const a=ids[j],b=ids[ids.length-1-j];games.push(round%2?[b,a]:[a,b])}rounds.push(games);ids.splice(1,0,ids.pop())}return [...rounds,...rounds.map(games=>games.map(([a,b])=>[b,a]))]}
export const seasonRounds=season=>fixtures(getLeague(season.leagueId)).length;
export function createSeason(leagueId,teamId,seed=Math.floor(Math.random()*1000000)){const league=LEAGUES.find(l=>l.id===leagueId),team=league?.teams.find(t=>t.id===teamId);if(!team)throw new Error('Unknown league or team');return {seed,leagueId,teamId,week:0,tactic:'balanced',results:[],players:{},names:{},world:Object.fromEntries(LEAGUES.filter(l=>l.id!==leagueId).map(l=>[l.id,{seed,results:[],players:{}}])),cup:null,history:[]}}
export function currentFixture(season){return fixtures(getLeague(season.leagueId))[season.week]?.find(pair=>pair.includes(season.teamId))}
function dice(seed){let x=Math.sin(seed*127.1+78.3)*43758.5453;return x-Math.floor(x)}
const hash=s=>[...s].reduce((n,c)=>(n*31+c.charCodeAt(0))%100000,0);
export function simulate(a,b,week,forcedScore,seasonSeed=0,tactics=['balanced','balanced']){const profiles=tactics.map(t=>t==='press'?{attack:.18,defense:-.18,shots:2,passes:1.04}:t==='counter'?{attack:-.04,defense:.12,shots:-1,passes:.88}:{attack:0,defense:0,shots:0,passes:1});const ta=getTeam(a),tb=getTeam(b),seed=week*79+hash(a)*19+hash(b)*37+seasonSeed*101,score=forcedScore??[Math.max(0,Math.round(1.15+profiles[0].attack-profiles[1].defense+(ta.strength-tb.strength)*3+(dice(seed)-.5)*3)),Math.max(0,Math.round(.95+profiles[1].attack-profiles[0].defense+(tb.strength-ta.strength)*3+(dice(seed+1)-.5)*3))],shots=score.map((n,i)=>n+5+profiles[i].shots+Math.floor(dice(seed+i+2)*8)),saves=[Math.round((shots[1]-score[1])*(.6+dice(seed+5)*.25)),Math.round((shots[0]-score[0])*(.6+dice(seed+6)*.25))],onTarget=[score[0]+saves[1],score[1]+saves[0]],passes=[Math.round((18+Math.floor(dice(seed+7)*20))*profiles[0].passes),Math.round((18+Math.floor(dice(seed+8)*20))*profiles[1].passes)];return {score,stats:{shots,onTarget,passes,passesCompleted:passes.map((n,i)=>Math.round(n*(.65+dice(seed+i+9)*.2))),crosses:[4+Math.floor(dice(seed+11)*5),4+Math.floor(dice(seed+12)*5)],tackles:[8+Math.floor(dice(seed+13)*6),8+Math.floor(dice(seed+14)*6)],fouls:[1+Math.floor(dice(seed+15)*3),1+Math.floor(dice(seed+16)*3)],yellows:[dice(seed+17)>.7?1:0,dice(seed+18)>.7?1:0],reds:[dice(seed+19)>.98?1:0,dice(seed+20)>.98?1:0],saves}}}
export function addPlayer(state,teamId,index,stat){const key=`${teamId}:${index}`,current={goals:0,assists:0,shots:0,shotsOnTarget:0,passes:0,passesCompleted:0,crosses:0,tackles:0,touches:0,fouls:0,yellows:0,reds:0,saves:0,distance:0,possession:0,headers:0,bicycles:0,forwardPasses:0,interceptions:0,tackleAttempts:0,playingSeconds:0,keyPasses:0,blocks:0,turnovers:0,crossesCompleted:0,carryDistance:0,headerGoals:0,bicycleGoals:0,penaltyGoals:0,...state.players[key]};for(const field of Object.keys(current))current[field]+=stat?.[field]??0;state.players[key]=current}
export function addSimulatedPlayers(state,teamId,side,score,stats,week){const players=Array.from({length:6},()=>({})),add=(field,count,start=1)=>{for(let i=0;i<count;i++){const p=players[start+i%(6-start)];p[field]=(p[field]??0)+1}};add('goals',score,1+week%5);add('assists',Math.max(0,score-1),2);add('shotsOnTarget',stats.onTarget[side]-score);for(const p of players)p.shots=(p.shots??0)+(p.shotsOnTarget??0)+(p.goals??0);add('shots',stats.shots[side]-stats.onTarget[side]);for(const p of players)p.shotsOnTarget=(p.shotsOnTarget??0)+(p.goals??0);for(const [field,start] of [['passes',0],['passesCompleted',0],['crosses',1],['tackles',1],['fouls',1]])add(field,stats[field][side],start);add('yellows',stats.yellows[side]);add('reds',stats.reds[side]);add('forwardPasses',Math.round(stats.passesCompleted[side]*.3));add('interceptions',Math.round(stats.tackles[side]*.3));add('keyPasses',Math.min(stats.shots[side],Math.round(stats.passesCompleted[side]*.2)));players.forEach(p=>{p.playingSeconds=180;p.tackleAttempts=Math.ceil((p.tackles??0)*1.6)});players[0].saves=stats.saves[side];players.forEach((p,i)=>addPlayer(state,teamId,i,p))}
export function orientStats(stats,homeIsUser){if(!stats)return null;const detail={};for(const field of Object.keys(stats))if(Array.isArray(stats[field])&&stats[field].length===2)detail[field]=homeIsUser?[...(stats[field]??[0,0])]:[...(stats[field]??[0,0])].reverse();return detail}
export function recordSimulated(state,home,away,week,phase){const {score,stats}=simulate(home,away,week,undefined,state.seed??0,[home===state.teamId?state.tactic??'balanced':'balanced',away===state.teamId?state.tactic??'balanced':'balanced']);state.results.push({week,home,away,score,stats,source:'simulated',...(phase?{phase}:{})});addSimulatedPlayers(state,home,0,score[0],stats,week);addSimulatedPlayers(state,away,1,score[1],stats,week)}
export function completeWeek(season,score,matchStats,matchTeamStats,report=null){const league=getLeague(season.leagueId);if(!fixtures(league)[season.week]||(score!==null&&(!Array.isArray(score)||score.length!==2)))throw new Error('No match to complete');for(const source of season.world?LEAGUES:[league]){const state=source.id===season.leagueId?season:season.world[source.id];for(const [home,away] of fixtures(source)[season.week]){const own=source.id===season.leagueId&&(home===season.teamId||away===season.teamId);if(!own||score===null){recordSimulated(state,home,away,season.week);continue}const homeIsUser=home===season.teamId,opponent=homeIsUser?away:home,result=homeIsUser?score:[score[1],score[0]],stats=orientStats(matchTeamStats,homeIsUser)??simulate(home,away,season.week,result,season.seed??0).stats;state.results.push({week:season.week,home,away,score:result,stats,source:'played',...(report?{report}:{})});if(matchStats)for(let i=0;i<6;i++){addPlayer(state,season.teamId,i,matchStats[i]);addPlayer(state,opponent,i,matchStats[i+6])}else{addSimulatedPlayers(state,home,0,result[0],stats,season.week);addSimulatedPlayers(state,away,1,result[1],stats,season.week)}}}season.week++;if(season.week===seasonRounds(season)){season.awards=leagueAwards(season);season.records=seasonRecords(season)}return season}
export const simulateWeek=season=>completeWeek(season,null);
export function standings(season,leagueId=season.leagueId){const league=getLeague(leagueId),state=leagueId===season.leagueId?season:season.world?.[leagueId],rows=league.teams.map(t=>({id:t.id,name:t.name,played:0,win:0,draw:0,loss:0,for:0,against:0,points:0}));for(const {home,away,score:[h,a]} of state?.results??[]){const x=rows.find(r=>r.id===home),y=rows.find(r=>r.id===away);x.played++;y.played++;x.for+=h;x.against+=a;y.for+=a;y.against+=h;if(h>a){x.win++;y.loss++;x.points+=3}else if(a>h){y.win++;x.loss++;y.points+=3}else{x.draw++;y.draw++;x.points++;y.points++}}return rows.sort((a,b)=>b.points-a.points||(b.for-b.against)-(a.for-a.against)||b.for-a.for)}
export function playerRows(state){return Object.entries(state.players).map(([id,stats])=>{const cut=id.lastIndexOf(':'),teamId=id.slice(0,cut),index=+id.slice(cut+1);return {teamId,index,name:state.names?.[id]??roster(teamId)[index],team:getTeam(teamId)?.name??teamId,...stats}})}
export function leaders(season){return playerRows(season).sort((a,b)=>b.goals-a.goals||b.assists-a.assists).slice(0,8)}
export function assistLeaders(season){return playerRows(season).sort((a,b)=>b.assists-a.assists||b.goals-a.goals).slice(0,6)}
export function keeperLeaders(season){return getLeague(season.leagueId).teams.map(team=>{let cleanSheets=0,conceded=0;for(const r of season.results){const side=r.home===team.id?0:r.away===team.id?1:-1;if(side>=0){conceded+=r.score[1-side];if(!r.score[1-side])cleanSheets++}}const saves=season.players[`${team.id}:0`]?.saves??0;return {name:season.names?.[`${team.id}:0`]??roster(team.id)[0],team:team.name,saves,cleanSheets,conceded,saveRate:saves+conceded?Math.round(saves/(saves+conceded)*100):null}}).sort((a,b)=>b.saves-a.saves)}
export function seasonSummary(season){const summary={played:0,wins:0,draws:0,losses:0,goalsFor:0,goalsAgainst:0,shots:0,onTarget:0,passes:0,passesCompleted:0,crosses:0,tackles:0,fouls:0,yellows:0,reds:0,saves:0,cleanSheets:0};for(const result of season.results){const side=result.home===season.teamId?0:result.away===season.teamId?1:-1;if(side<0)continue;const goals=result.score[side],against=result.score[1-side];summary.played++;summary.goalsFor+=goals;summary.goalsAgainst+=against;if(goals>against)summary.wins++;else if(goals<against)summary.losses++;else summary.draws++;if(against===0)summary.cleanSheets++;for(const field of ['shots','onTarget','passes','passesCompleted','crosses','tackles','fouls','yellows','reds','saves'])summary[field]+=result.stats?.[field]?.[side]??0}summary.tackles=Object.entries(season.players).filter(([key])=>key.startsWith(`${season.teamId}:`)).reduce((n,[,p])=>n+(p.tackles??0),0);return summary}
export function leagueAwards(season){const rows=playerRows(season),best=(field,filter=()=>true)=>[...rows].filter(filter).sort((a,b)=>b[field]-a[field]||b.goals-a.goals)[0],impact=r=>r.goals*3+r.assists*2+r.tackles*.15+r.saves*.3;return {champion:standings(season)[0]?.id,goldenBoot:best('goals',r=>r.index>0),playmaker:best('assists',r=>r.index>0),goldenGlove:[...keeperLeaders(season)].sort((a,b)=>b.cleanSheets-a.cleanSheets||b.saveRate-a.saveRate||b.saves-a.saves)[0],mvp:[...rows].sort((a,b)=>{const peers=r=>rows.filter(p=>(p.index===0?'g':p.index<3?'d':p.index<5?'m':'f')===(r.index===0?'g':r.index<3?'d':r.index<5?'m':'f')),relative=r=>impact(r)/(peers(r).reduce((n,p)=>n+impact(p),0)/peers(r).length||1);return relative(b)-relative(a)})[0]}}
export function seasonRecords(season){const games=season.results.filter(r=>r.home===season.teamId||r.away===season.teamId);let wins=0,streak=0,biggestWin=0,mostGoals=0;for(const game of games){const i=game.home===season.teamId?0:1,diff=game.score[i]-game.score[1-i];wins=diff>0?wins+1:0;streak=Math.max(streak,wins);biggestWin=Math.max(biggestWin,diff);mostGoals=Math.max(mostGoals,game.score[i])}return {winStreak:streak,biggestWin,mostGoals}}
