import assert from 'node:assert/strict';
import {createSeason,completeWeek} from './league.mjs';
import {makeMatchNews,addMatchNews} from './news.mjs';
import {exportBackup,importBackup,makeClubSlot} from './save-slots.mjs';

const before=createSeason('england','arsenal',1),after=structuredClone(before);
completeWeek(after,[2,1]);
const base={before,after,mode:'club',score:[2,1],opponent:'Chelsea',stats:{shots:[7,4],onTarget:[3,2],saves:[1,1]}};
const article=makeMatchNews(base);
assert.match(article.headline,/击败/);
assert.match(article.lead,/2 : 1/);
assert.match(article.lead,/第 1 轮/);
assert.doesNotMatch(article.body,/从第/);
assert.deepEqual(article.stats.shots,[7,4]);
addMatchNews(after,article);
assert.equal(after.news[0].id,article.id);
const backup=importBackup(exportBackup({version:2,active:0,slots:[makeClubSlot(after),null,null]}));
assert.equal(backup.slots[0].season.news[0].headline,article.headline);
const career=makeMatchNews({...base,mode:'career',careerBefore:{stats:{goals:0}},careerAfter:{name:'新星',lastMatch:{goals:1,assists:0,rating:8.2}}});
assert.match(career.headline,/生涯首球/);
assert.match(career.body,/8\.2/);
const simulated=makeMatchNews({...base,source:'simulated'});
assert.equal(simulated.source,'simulated');
const cupBefore={...before,cup:{phase:'final'}},cupAfter={...after,cup:{phase:'complete',champion:'arsenal',results:[{}]}};
const cup=makeMatchNews({...base,before:cupBefore,after:cupAfter,competition:'cup'});
assert.match(cup.headline,/杯赛冠军/);
const penalty=makeMatchNews({...base,score:[1,1],shootout:{winner:'arsenal',score:[4,3]}});
assert.match(penalty.headline,/点球淘汰/);
console.log('PASS: match news facts, career milestone, simulation and cup results.');
