import React from 'react';
import {PRACTICE_SCENARIOS} from './practice.mjs';
import {OUTCOMES,rate} from './experience.mjs';
import {ShotDetails} from './experience.jsx';

function PracticeDiagram({scenario}){const paths={solo:'M70 62L170 62',side:'M85 95L172 45',receive:'M25 30L85 62L172 62',cross:'M50 105Q110 10 170 62'};return <svg className="practice-diagram" viewBox="0 0 200 120" aria-hidden="true"><path d="M5 5h190v110H5z" fill="#283f37" stroke="#9cbbb0"/><path d="M155 30h40v60h-40zM177 45h18v30h-18z" stroke="#9cbbb0" fill="none"/><path d={paths[scenario]} stroke="#c8fa73" strokeWidth="3" strokeDasharray={scenario==='cross'?'4 5':undefined} fill="none"/><rect x={scenario==='side'?75:60} y={scenario==='side'?85:52} width="16" height="16" fill="#85c9ed"/><circle cx="170" cy="62" r="5" fill="#f2f2ea"/></svg>}

export function PracticeSetup({options,onChange,onStart,difficulties}){
  const set=(key,value)=>onChange({...options,[key]:value});
  return <section className="panel practice-setup"><div className="panel-label">TRAINING GROUND</div><h2>找到你的进球方式</h2><div className="practice-scenarios">{Object.entries(PRACTICE_SCENARIOS).map(([id,name])=><button key={id} className={options.scenario===id?'active':''} aria-pressed={options.scenario===id} onClick={()=>set('scenario',id)}><PracticeDiagram scenario={id}/><strong>{name}</strong><span>{{solo:'练习时机与门前选择',side:'从两侧寻找射门角度',receive:'接球后快速完成射门',cross:'判断落点，头球或倒钩'}[id]}</span></button>)}</div><div className="practice-fields"><label>门将与防守难度<select value={options.difficulty} onChange={e=>set('difficulty',+e.target.value)}>{difficulties.map((name,i)=><option key={i} value={i}>{name}</option>)}</select></label><label>起始距离<select value={options.range} onChange={e=>set('range',+e.target.value)}><option value="100">近 · 10m</option><option value="130">标准 · 13m</option><option value="220">中距离 · 22m</option></select></label>{options.scenario!=='solo'&&<label>来球 / 射门侧<select value={options.side} onChange={e=>set('side',+e.target.value)}><option value="-1">上侧</option><option value="1">下侧</option></select></label>}{options.scenario==='receive'&&<label className="practice-check"><input type="checkbox" checked={options.defender} onChange={e=>set('defender',e.target.checked)}/>加入一名防守者</label>}<label className="practice-check"><input type="checkbox" checked={options.assist} onChange={e=>set('assist',e.target.checked)}/>显示传中预计落点</label></div><p>每组 10 次。WASD 移动，鼠标瞄准，左键射门。传中接近时左键头球，Shift＋左键倒钩。距离按球场比例估算。</p><button className="primary" onClick={onStart}>开始练习</button><p>训练不计入赛季、经验或荣誉。</p></section>;
}

export function PracticePanel({match,onNext,onReset,onSettings,onReport}){
  const done=match.attempts.length,goals=match.attempts.filter(a=>a.outcome==='goal').length,shot=match.shotLog.length>match.startShot?match.shotLog.at(-1):null;
  return <div className="panel practice-panel"><div className="panel-label">TRAINING / {done}/10</div><h2>{PRACTICE_SCENARIOS[match.options.scenario]}</h2><div className="practice-count"><b>{goals}</b><span>进球 · 练习成功率 {rate(goals,done)}</span></div><div className="attempt-strip" aria-label="本组十次练习结果">{Array.from({length:10},(_,i)=>{const attempt=match.attempts[i];return <button key={i} disabled={attempt?.shotId==null} className={attempt?.outcome??'empty'} title={attempt?OUTCOMES[attempt.outcome]:'未练习'} aria-label={`第 ${i+1} 次：${attempt?OUTCOMES[attempt.outcome]:'未练习'}`} onClick={()=>onReport(match.report(),attempt.shotId)}>{attempt?attempt.outcome==='goal'?'★':attempt.outcome==='saved'?'●':attempt.outcome==='blocked'?'×':attempt.outcome==='wide'?'△':'—':i+1}</button>})}</div><div className="practice-totals">{['saved','blocked','wide','lost','foul','whistle'].map(result=><span key={result}>{OUTCOMES[result]} <b>{match.attempts.filter(a=>a.outcome===result).length}</b></span>)}</div>{shot&&<ShotDetails shot={shot}/>}<div className="practice-actions"><button className="primary" disabled={match.state!=='ended'||done>=10} onClick={onNext}>再试一次</button><button className="subtle" onClick={onReset}>重置整组</button><button className="subtle" disabled={!match.shotLog.length} onClick={()=>onReport(match.report())}>查看本组射门图</button><button className="subtle" onClick={onSettings}>更换练习</button></div><p>{done>=10?'本组已完成，可查看分布图或重置整组。':'每次最多 12 秒。接球与传中场景自动发球。'}</p></div>;
}
