import {STYLES} from './experience.mjs';
import {LEAGUES,getLeague,getTeam,seasonRounds,leagueAwards,seasonRecords,prepareSeason} from './league.mjs';

export const SAVE_KEY='pixel-pitch-saves-v2';
export const LEGACY_KEY='pixel-pitch-season-v1';

function validSeason(season){return !!season&&getLeague(season.leagueId)?.teams.some(team=>team.id===season.teamId)&&Number.isInteger(season.week)&&season.week>=0&&season.week<=seasonRounds(season)&&Array.isArray(season.results)&&!!season.players}
function validCareer(player){return !!player&&typeof player.name==='string'&&['forward','midfielder','defender'].includes(player.position)&&Number.isInteger(player.index)&&!!player.attributes&&!!player.stats}
function blank(){return {version:2,active:null,slots:[null,null,null]}}

export function loadSaveData(storage=localStorage){
  try{
    const saved=JSON.parse(storage.getItem(SAVE_KEY));
    if(saved?.version===2&&Array.isArray(saved.slots)){
      const slots=Array.from({length:3},(_,index)=>{const slot=saved.slots[index];if(validSeason(slot?.season)&&(slot.mode==='club'||slot.mode==='career'&&validCareer(slot.player))){prepareSeason(slot.season,slot.player);return slot}return null});
      const active=Number.isInteger(saved.active)&&slots[saved.active]?saved.active:null;
      return {version:2,active,slots};
    }
    const legacy=JSON.parse(storage.getItem(LEGACY_KEY));
    if(validSeason(legacy)){
      prepareSeason(legacy);const now=Date.now(),data={version:2,active:0,slots:[makeClubSlot(legacy,1,180,now),null,null]};
      storage.setItem(SAVE_KEY,JSON.stringify(data));
      return data;
    }
  }catch{}
  return blank();
}

export function makeClubSlot(season,difficulty=1,duration=180,now=Date.now()){return {mode:'club',season,difficulty,duration,createdAt:now,updatedAt:now}}
export function makeCareerSlot(season,player,difficulty=1,duration=180,now=Date.now()){return {mode:'career',season,player,difficulty,duration,createdAt:now,updatedAt:now}}
export function saveSaveData(data,storage=localStorage){storage.setItem(SAVE_KEY,JSON.stringify(data))}

export function exportBackup(data){return JSON.stringify({version:2,active:data.active,slots:data.slots})}
export function importBackup(text){
  if(typeof text!=='string'||text.length>8000000)throw new Error('存档文件过大');
  let data;try{data=JSON.parse(text)}catch{throw new Error('文件不是有效的存档 JSON')}
  if(data?.version!==2||!Array.isArray(data.slots)||data.slots.length!==3)throw new Error('存档版本或存档槽数量不正确');
  const object=o=>o&&typeof o==='object'&&!Array.isArray(o);
  const finite=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<1000000000;
  const finiteStats=o=>object(o)&&Object.values(o).every(finite);
  const pair=p=>Array.isArray(p)&&p.length===2&&p[0]!==p[1]&&p.every(id=>getTeam(id));
  const stats=o=>o==null||object(o)&&['shots','onTarget','passes','passesCompleted','crosses','tackles','fouls','yellows','reds','saves'].every(k=>Array.isArray(o[k])&&o[k].length===2&&o[k].every(finite));
  const shotExtra=s=>['power','speed','distance'].every(k=>s[k]==null||finite(s[k])&&s[k]<=(k==='power'?1:k==='speed'?2000:150))&&['aim','end'].every(k=>s[k]==null||object(s[k])&&['x','y'].every(c=>finite(s[k][c])&&s[k][c]<=1))&&(s.trajectory==null||object(s.trajectory)&&['x','y'].every(k=>Number.isFinite(s.trajectory[k])&&Math.abs(s.trajectory[k])<=2000))&&['resolvedBy','keeper'].every(k=>s[k]==null||Number.isInteger(s[k])&&s[k]>=0&&s[k]<12);
  const report=r=>r==null||object(r)&&r.version===1&&(r.playerIds==null||Array.isArray(r.playerIds)&&r.playerIds.length===12&&r.playerIds.every(id=>typeof id==='string'&&id.length<=100))&&(r.careerIndex==null||[1,3,5].includes(r.careerIndex))&&Array.isArray(r.teams)&&r.teams.length===2&&r.teams.every(n=>typeof n==='string'&&n.length<=100)&&Array.isArray(r.score)&&r.score.length===2&&r.score.every(n=>Number.isInteger(n)&&n>=0&&n<1000)&&[120,180,300].includes(r.duration)&&Array.isArray(r.numbers)&&r.numbers.length===12&&r.numbers.every(n=>Number.isInteger(n)&&n>=1&&n<=99)&&Array.isArray(r.shots)&&r.shots.length<=2000&&r.shots.every((s,i)=>object(s)&&s.id===i&&Number.isInteger(s.player)&&s.player>=0&&s.player<12&&s.team===Math.floor(s.player/6)&&finite(s.minute)&&s.minute<=90&&[1,2].includes(s.half)&&['x','y'].every(k=>finite(s[k])&&s[k]<=1)&&['normal','header','bicycle','penalty'].includes(s.type)&&['goal','saved','blocked','wide','whistle','pending'].includes(s.outcome)&&typeof s.pressured==='boolean'&&['高','中','低'].includes(s.quality)&&shotExtra(s))&&Array.isArray(r.events)&&r.events.length<=4000&&r.events.every(e=>object(e)&&['shot','goal','foul','yellow','red'].includes(e.type)&&finite(e.minute)&&e.minute<=90&&[0,1].includes(e.team)&&(e.player===null||Number.isInteger(e.player)&&e.player>=0&&e.player<12)&&(e.labels===undefined||Array.isArray(e.labels)&&e.labels.length<=8&&e.labels.every(t=>['扳平比分','反超比分','最后阶段进球','远射破门','头球破门','倒钩破门','点球破门','生涯首球'].includes(t)))&&(e.score===undefined||Array.isArray(e.score)&&e.score.length===2&&e.score.every(n=>Number.isInteger(n)&&n>=0&&n<1000))&&(e.shotId===undefined||Number.isInteger(e.shotId)&&e.shotId>=0&&e.shotId<r.shots.length))&&(r.stats===undefined||Array.isArray(r.stats)&&r.stats.length===12&&r.stats.every(finiteStats))&&(r.heat===undefined||Array.isArray(r.heat)&&r.heat.length===12&&r.heat.every(rows=>Array.isArray(rows)&&rows.length===4&&rows.every(row=>Array.isArray(row)&&row.length===96&&row.every(finite))));
  const state=o=>object(o)&&Array.isArray(o.results)&&o.results.every(r=>object(r)&&pair([r.home,r.away])&&Array.isArray(r.score)&&r.score.length===2&&r.score.every(n=>Number.isInteger(n)&&n>=0&&n<1000)&&stats(r.stats)&&report(r.report))&&object(o.players)&&Object.entries(o.players).every(([id,row])=>{const cut=id.lastIndexOf(':');return ((getTeam(id.slice(0,cut))&&/^[0-5]$/.test(id.slice(cut+1)))||/^p:[a-z0-9-]+:[0-5](?::r[1-9][0-9]*)?$/.test(id))&&finiteStats(row)})&&(o.names==null||object(o.names)&&Object.values(o.names).every(n=>typeof n==='string'&&n.length<=100));
  const identity=s=>s.rosterIds==null&&s.playerData==null||object(s.rosterIds)&&object(s.playerData)&&LEAGUES.flatMap(l=>l.teams).every(team=>Array.isArray(s.rosterIds[team.id])&&s.rosterIds[team.id].length===6)&&Object.entries(s.rosterIds).every(([team,ids])=>getTeam(team)&&Array.isArray(ids)&&ids.length===6&&ids.every((id,index)=>typeof id==='string'&&s.playerData[id]?.id===id&&s.playerData[id]?.teamId===team&&s.playerData[id]?.position===index))&&new Set(Object.values(s.rosterIds).flat()).size===LEAGUES.flatMap(l=>l.teams).length*6&&Object.values(s.playerData).every(p=>object(p)&&typeof p.id==='string'&&typeof p.name==='string'&&p.name.length<=100&&getTeam(p.teamId)&&Number.isInteger(p.position)&&p.position>=0&&p.position<6&&object(p.attributes)&&['shooting','passing','defense','goalkeeping'].every(k=>Number.isInteger(p.attributes[k])&&p.attributes[k]>=1&&p.attributes[k]<=99));
  for(const slot of data.slots){if(slot===null)continue;
    if(!validSeason(slot?.season)||!['club','career'].includes(slot.mode)||![0,1,2,3].includes(slot.difficulty)||![120,180,300].includes(slot.duration))throw new Error('存档中的球队或比赛设置无效');
    const s=slot.season,league=getLeague(s.leagueId);if(s.news!==undefined&&(!Array.isArray(s.news)||s.news.length>80||s.news.some(n=>!object(n)||typeof n.id!=='string'||n.id.length>100||!Number.isInteger(n.year)||n.year<1||!['club','career'].includes(n.mode)||!['league','cup'].includes(n.competition)||!['played','simulated'].includes(n.source)||!['result','title','milestone','table'].includes(n.type)||![n.headline,n.lead,n.body,n.team,n.opponent].every(t=>typeof t==='string'&&t.length<=600)||!Array.isArray(n.score)||n.score.length!==2||!n.score.every(finite))))throw new Error('赛后新闻数据无效');if(s.godMode!==undefined&&typeof s.godMode!=='boolean'||s.teamNames!==undefined&&(!object(s.teamNames)||Object.entries(s.teamNames).some(([id,name])=>!getTeam(id)||typeof name!=='string'||!name.trim()||name.length>60))||s.godEdits!==undefined&&(!Array.isArray(s.godEdits)||s.godEdits.length>50||s.godEdits.some(e=>!object(e)||!['team','player','stats'].includes(e.kind)||typeof e.detail!=='string'||e.detail.length>500||!Number.isInteger(e.at)||e.at<0||e.at>10000000000000)))throw new Error('God Mode 数据无效');if(!state(s)||!identity(s)||s.results.some(r=>!league.teams.some(t=>t.id===r.home)||!league.teams.some(t=>t.id===r.away))||(s.seed!==undefined&&!finite(s.seed))||(s.history!==undefined&&(!Array.isArray(s.history)||s.history.some(h=>!object(h)))))throw new Error('存档比赛数据无效');
    if(s.playerData&&Object.values(s.playerData).some(p=>p.number!==undefined&&(!Number.isInteger(p.number)||p.number<1||p.number>99))||s.rosterIds&&Object.values(s.rosterIds).some(ids=>ids.some((id,i)=>ids.some((other,j)=>i!==j&&s.playerData[id]?.number!==undefined&&s.playerData[id]?.number===s.playerData[other]?.number))))throw new Error('球衣号码无效或重复');
    if(s.world&&( !object(s.world)||Object.keys(s.world).some(id=>!getLeague(id))||!Object.entries(s.world).every(([id,w])=>state(w)&&w.results.every(r=>getLeague(id).teams.some(t=>t.id===r.home)&&getLeague(id).teams.some(t=>t.id===r.away)))||['england','spain','germany','italy','france'].some(id=>id!==s.leagueId&&!s.world[id])))throw new Error('其他联赛数据无效');
    const c=s.cup;if(c&&(!state(c)||!Array.isArray(c.teams)||c.teams.length!==10||new Set(c.teams).size!==10||c.teams.some(id=>!getTeam(id))||!['league','semi','final','complete'].includes(c.phase)||!Number.isInteger(c.round)||c.round<0||c.round>3||!Array.isArray(c.fixtures)||c.fixtures.length!==4||c.fixtures.some(round=>!Array.isArray(round)||round.length!==5||!round.every(p=>pair(p)&&p.every(id=>c.teams.includes(id))))||c.results.some(r=>!c.teams.includes(r.home)||!c.teams.includes(r.away))||c.phase==='semi'&&(!Array.isArray(c.semis)||c.semis.length!==2||!c.semis.every(pair))||c.phase==='final'&&!pair(c.final)||c.phase==='complete'&&!c.teams.includes(c.champion)))throw new Error('杯赛数据无效');
    if(slot.mode==='career'){
      const p=slot.player;
      if(p.clubProgress!==undefined&&(!object(p.clubProgress)||Object.keys(p.clubProgress).length>100||Object.entries(p.clubProgress).some(([id,r])=>!getTeam(id)||!object(r)||!Number.isInteger(r.appearances)||r.appearances<0||!finite(r.points)||r.points>r.appearances*6||!Number.isInteger(r.goodGames)||r.goodGames<0||r.goodGames>r.appearances||!Array.isArray(r.titles)||r.titles.length>2000||new Set(r.titles).size!==r.titles.length||r.titles.some(n=>typeof n!=='string'||!/^([1-9]\d*):(league|cup)$/.test(n)))))throw new Error('球队角色进度无效');
      if(p.progressXp!==undefined&&(!finite(p.progressXp)||p.progressXp>=Math.min(300,100+Math.max(0,p.level-5)*15)))throw new Error('球员升级进度无效');
      if(p.signatureMatchId!==undefined&&(!Number.isInteger(p.signatureMatchId)||!p.memories?.some(r=>r.matchId===p.signatureMatchId)))throw new Error('生涯代表作无效');
      if(p.memories!==undefined&&(!Array.isArray(p.memories)||p.memories.length>30||new Set(p.memories.map(r=>r?.matchId)).size!==p.memories.length||p.memories.some(r=>!object(r)||!Number.isInteger(r.matchId)||r.matchId<1||!Number.isInteger(r.season)||r.season<1||!['league','cup'].includes(r.competition)||typeof r.opponent!=='string'||r.opponent.length>100||!Array.isArray(r.score)||r.score.length!==2||!r.score.every(finite)||!['rating','goals','assists'].every(k=>finite(r[k]))||r.rating<4||r.rating>10||!Array.isArray(r.reasons)||r.reasons.length>6||r.reasons.some(n=>typeof n!=='string'||n.length>30)||!report(r.report))))throw new Error('比赛收藏数据无效');
      if(p.id!==undefined&&(typeof p.id!=='string'||!s.playerData?.[p.id]))throw new Error('球员身份数据无效');
      if(!validCareer(p)||!finiteStats(p.attributes)||!['shooting','passing','defense'].every(k=>p.attributes[k]>0&&p.attributes[k]<=99)||!finiteStats(p.stats)||!Number.isInteger(p.number)||p.number<2||p.number>99||p.index!==({forward:5,midfielder:3,defender:1})[p.position]||!Number.isInteger(p.level)||p.level<1||!finite(p.xp)||p.name.length>10)throw new Error('球员数据无效');
      if(p.lastMatch&&(!object(p.lastMatch)||!['goals','assists','shots','shotsOnTarget','passes','passesCompleted','tackles','rating','xpGain'].every(k=>finite(p.lastMatch[k]))||!Array.isArray(p.lastMatch.score)||p.lastMatch.score.length!==2||!p.lastMatch.score.every(finite)||p.lastMatch.growth&&!finiteStats(p.lastMatch.growth)||p.lastMatch.objective&&(!object(p.lastMatch.objective)||typeof p.lastMatch.objective.label!=='string'||typeof p.lastMatch.objective.complete!=='boolean')))throw new Error('上一场比赛数据无效');
      if(p.appearance&&(!object(p.appearance)||!Object.entries(p.appearance).every(([key,value])=>['skin','hair','shoes'].includes(key)?typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value):key==='hairstyle'?Number.isInteger(value)&&value>=0&&value<6:key==='celebration'?Number.isInteger(value)&&value>=0&&value<3:key==='sleeve'?['short','long','band'].includes(value):false)))throw new Error('球员外观无效');
      if(p.style!=null&&!STYLES[p.position].some(s=>s.id===p.style)||p.bio!==undefined&&(typeof p.bio!=='string'||p.bio.length>40)||p.honors!==undefined&&(!Array.isArray(p.honors)||p.honors.length>100||p.honors.some(n=>typeof n!=='string'||n.length>100))||p.history!==undefined&&(!Array.isArray(p.history)||p.history.length>2000||p.history.some(r=>!object(r)||!['league','cup'].includes(r.competition)||!Number.isInteger(r.season)||r.season<1||typeof r.opponent!=='string'||r.opponent.length>100||!finiteStats(Object.fromEntries(Object.entries(r).filter(([key])=>!['competition','season','opponent','report','score','growth','objective'].includes(key))))||!['goals','assists','shots','shotsOnTarget','passes','passesCompleted','tackles','rating','xpGain'].every(k=>finite(r[k]))||r.rating<4||r.rating>10||!Array.isArray(r.score)||r.score.length!==2||!r.score.every(finite)||!report(r.report))))throw new Error('球员风格或历史记录无效');
      if(p.seasonLedger!==undefined&&(!object(p.seasonLedger)||Object.keys(p.seasonLedger).length>1000||Object.entries(p.seasonLedger).some(([k,v])=>!/^\d+$/.test(k)||+k<1||!object(v)||!finiteStats(v)||!['appearances','goals','assists','tackles','ratingTotal','xpGain','wins','draws','losses'].every(f=>finite(v[f])))))throw new Error('生涯赛季汇总无效');
    }
    prepareSeason(s,slot.player);
    if(s.week===seasonRounds(s))s.awards=leagueAwards(s);else delete s.awards;if(s.week)s.records=seasonRecords(s);else delete s.records;
  }
  return {version:2,active:Number.isInteger(data.active)&&data.slots[data.active]?data.active:null,slots:data.slots};
}
