import React,{useState} from 'react';
import {careerTimeline,careerSeasonSummary,signatureMatch} from './career-story.mjs';
import {seasonRounds,standings} from './league.mjs';
import {teamName} from './identity.mjs';

export function SignatureMatch({career,onReport}){const row=signatureMatch(career);if(!row)return null;return <section className="signature-match panel"><div><h2>我的代表作</h2><p>第{row.season}赛季 · 对阵 {row.opponent}</p><strong>{row.score.join(' : ')}</strong><p>{row.goals}进球 · {row.assists}助攻 · 评分 {row.rating}</p><small>{row.reasons.join(' · ')}</small></div><button className="subtle" disabled={!row.report} onClick={()=>onReport(row.report)}>重温这场比赛 ↗</button></section>}

export function CareerTimeline({career,onReport}){
 const [year,setYear]=useState('all'),[scope,setScope]=useState('all'),[limit,setLimit]=useState(12),events=careerTimeline(career),years=[...new Set(events.map(r=>r.season))].sort((a,b)=>b-a),filtered=events.filter(r=>(year==='all'||r.season===+year)&&(scope==='all'||r.labels.some(n=>scope==='growth'?n.startsWith('成长'):!n.startsWith('成长'))));
 return <section className="panel career-timeline"><div className="chart-heading"><h2>你的生涯时间线</h2><div className="story-filters"><label>赛季<select value={year} onChange={e=>{setYear(e.target.value);setLimit(12)}}><option value="all">全部赛季</option>{years.map(n=><option key={n} value={n}>第{n}赛季</option>)}</select></label><label>篇章<select value={scope} onChange={e=>{setScope(e.target.value);setLimit(12)}}><option value="all">全部篇章</option><option value="match">比赛里程碑</option><option value="growth">能力成长</option></select></label></div></div><p>从实际记录中寻找重要时刻。组织代表作需单场至少3次关键传球；防守代表作需抢断、拦截、封堵合计至少6次。</p>{events.length&&events.at(-1).matchId>1?<p>早期比赛详情不完整，仅呈现有据可查的篇章。</p>:null}<ol className="story-track">{filtered.slice(0,limit).map(r=><li key={r.matchId}><div className="story-marker" aria-hidden="true"/><div><small>第{r.season}赛季 · 生涯第{r.matchId}场 · {r.competition==='cup'?'欧洲冠军杯':'联赛'}</small><h3>{r.labels.join(' / ')}</h3><p>{r.opponent} · {r.score.join(' : ')} · 评分{r.rating}</p><button className="subtle" disabled={!r.report} onClick={()=>onReport(r.report)}>{r.report?'重温比赛 ↗':'仅保留比赛摘要'}</button></div></li>)}</ol>{!filtered.length&&<p>{events.length?'这个筛选下还没有篇章。':'完成首秀，在这里写下你的第一段足球故事。'}</p>}{filtered.length>limit&&<button className="subtle" onClick={()=>setLimit(limit+12)}>展开更早的12段篇章</button>}</section>
}
const metricNames={shots:'射门',shotsOnTarget:'射正',passes:'传球尝试',passesCompleted:'成功传球',keyPasses:'关键传球',tackles:'成功抢断',interceptions:'拦截',blocks:'射门封堵',turnovers:'丢失球权'};
export function SeasonRecap({career,season,onReport}){
 const current=(season.history?.length??0)+1,years=[...new Set([current,...(career.history??[]).map(r=>r.season),...Object.keys(career.seasonLedger??{}).map(Number)])].sort((a,b)=>b-a),[choice,setChoice]=useState(null),year=years.includes(choice)?choice:current,summary=careerSeasonSummary(career,year),past=season.history?.[year-1],complete=year<current||(season.week===seasonRounds(season)&&(!season.cup||season.cup.phase==='complete')),rank=year===current?standings(season).findIndex(r=>r.id===season.teamId)+1:null,champion=year===current?(season.week===seasonRounds(season)?standings(season)[0]?.id:null):past?.champion,cupChampion=year===current?season.cup?.champion:past?.cupChampion;
 return <section className="panel season-recap"><div className="chart-heading"><h2>{complete?'赛季总结':'赛季进行中'}</h2><label>查看赛季<select value={year} onChange={e=>setChoice(+e.target.value)}>{years.map(n=><option key={n} value={n}>第{n}赛季{n===current?' · 当前':''}</option>)}</select></label></div><p>{complete?'这一章已经落幕，你的贡献与成长留在这里。':'每场正式比赛结束后更新，杯赛表现也计入球员汇总。'}{rank!==null&&season.week>0?` 当前联赛第${rank}名。`:''}</p>{summary?<><div className="recap-results"><strong>{summary.wins}胜 {summary.draws}平 {summary.losses}负</strong><span>{summary.appearances}次出场 · 均分{summary.rating.toFixed(1)} · +{summary.xp}XP</span><span>{summary.goals}进球 / {summary.assists}助攻</span></div><h3>{summary.detailedComplete?'这一季，能力如何改变':'保留记录中的能力增长'}</h3><div className="season-growth">{Object.entries(summary.growth).map(([k,n])=><div key={k}><span>{{shooting:'射门',passing:'传球',defense:'防守'}[k]}</span><strong>{n===null?'未记录':`+${n}`}</strong><meter aria-label={({shooting:'射门',passing:'传球',defense:'防守'}[k])+'赛季能力增长'} min="0" max="99" value={n??0}/></div>)}</div><details className="recap-detail"><summary>展开赛季贡献 · {summary.rows.length}场有详细记录</summary><p>{summary.detailedComplete?'统计来自本赛季保存的逐场记录。':'详细数据仅覆盖保留的比赛，赛季汇总可能覆盖更多场次。'}缺失项目显示“未记录”。</p><div className="recap-metrics">{summary.contributions.map(([k,n])=><div key={k}><span>{metricNames[k]}</span><strong>{n===null?'未记录':n}</strong></div>)}</div></details><h3>本季高光 · 按评分排列</h3>{summary.best.map(r=><button className="journal-row" key={r.matchId} disabled={!r.report&&!career.memories?.find(m=>m.matchId===r.matchId)?.report} onClick={()=>onReport(r.report??career.memories.find(m=>m.matchId===r.matchId).report)}><span>{r.opponent}<small>{r.score.join(' : ')} · {r.goals}球 / {r.assists}助攻</small></span><b>{r.rating}</b></button>)}{complete&&<p>下一季目标：{career.position==='forward'?'提高射正与终结表现':career.position==='midfielder'?'创造更多关键传球机会':'增加有效防守，减少丢失球权'}。以本季数据作为比较起点。</p>}</>:<p>本赛季还没有球员比赛记录。完成一场正式比赛后生成总结。</p>}<div className="recap-honors"><h3>赛季荣誉</h3><p>联赛冠军：{champion?teamName(season,champion)??champion:'尚未决出 / 未记录'}</p><p>欧洲冠军杯：{cupChampion?teamName(season,cupChampion)??cupChampion:complete?'未获得 / 未记录':'尚未结束'}</p></div></section>
}
