import assert from 'node:assert/strict';
import {Match,FIELD,distance} from './engine.mjs';
import {tacticalPlan} from './tactics.mjs';
const normal=tacticalPlan('balanced',[0,0],0,.8),chase=tacticalPlan('balanced',[0,1],0,.8),protect=tacticalPlan('balanced',[1,0],0,.8);
assert.equal(normal.mentality,'normal');assert.equal(chase.mentality,'chase');assert.equal(protect.mentality,'protect');assert(chase.line>normal.line&&normal.line>protect.line);assert.equal(tacticalPlan('press',[0,1],0,.5).mentality,'normal');assert(tacticalPlan('press',[0,0],0,.2,3).line<tacticalPlan('press').line);
const pressure=m=>[0,1].map(t=>m.players.map((p,id)=>({p,id})).filter(({p,id})=>p.t===t&&p.i!==0&&m.active(id)&&!(t===0&&id===m.selected[0])).sort((a,b)=>distance(a.p,m.ball)-distance(b.p,m.ball)));
const runs={};for(const style of ['balanced','counter','press']){const game=new Match({tactic:style});game.kickoffId=null;game.ball.owner=3;game.players[3].x=480;game.players[3].y=FIELD.center;game.players[5].x=470;game.players[5].y=310;game.players[4].x=200;game.players[4].y=440;runs[style]=game.aiMove(4,game.players[3],pressure(game))[0]}assert(runs.counter>runs.press&&runs.press>runs.balanced,'styles must change actual support positions, not only labels');
let m=new Match({difficulty:3});m.time=m.duration*.8;m.score=[1,0];assert.equal(m.teamPlan(0).mentality,'protect');assert.equal(m.teamPlan(1).mentality,'chase');const oldStrength=[...m.strength];m.stats[9].reds=1;m.stats[10].reds=1;assert(m.pressers(1)<=2);assert.deepEqual(m.strength,oldStrength,'strategy must never silently boost attributes');
for(const half of [1,2]){m=new Match();m.half=half;m.reset(0);m.kickoffId=null;m.players[5].x=480;m.players[5].y=FIELD.center;m.players[3].x=480+m.direction(0)*100;m.players[3].y=365;m.players.slice(6).forEach(p=>{p.x=900;p.y=70});m.ball.owner=5;assert(m.kick(5,false,.4,3));assert.equal(m.giveGo.id,5);assert((m.giveGo.x-480)*m.direction(0)>0,'passer must move forward in either half');m.takeBall(3);const move=m.aiMove(5,m.players[3],pressure(m));assert(move[0]*m.direction(0)>0);m.reset(0);assert.equal(m.giveGo,null)}
m=new Match();m.ball.owner=11;m.ball.last=1;m.takeBall(3);assert.equal(m.attackStarted[0],m.time,'winning possession starts a counter window');
// A shared predicted rebound point guarantees one primary chaser per team.
m=new Match();m.ball={x:730,y:390,z:3,vx:-120,vy:130,vz:45,owner:null,last:1,kind:'parry',source:null};let choices=pressure(m),look=.18,point={x:730-120*look*.8,y:390+130*look*.8};for(let t=0;t<2;t++){const nearest=choices[t].slice().sort((a,b)=>distance(a.p,point)-distance(b.p,point))[0],move=m.aiMove(nearest.id,null,choices);assert(Math.abs(move[0]-(point.x-nearest.p.x))<.001);assert(Math.abs(move[1]-(point.y-nearest.p.y))<.001)}
m=new Match();m.state='playing';m.restart(0,FIELD.right-8,FIELD.top+8,'角球',0);const taker=m.ball.owner;m.time=.81;m.step(.02,[{},{}]);assert.equal(m.ball.owner,null,'an idle human-controlled corner taker must not trap the match in repeated corners');assert(m.passes[0]>0);assert.equal(m.setPiece,null);
m=new Match();m.state='playing';m.ball.owner=5;m.ball.x=FIELD.mid;m.ball.y=FIELD.center;m.players[5].x=FIELD.mid;m.players[5].y=FIELD.center;m.players[11].x=FIELD.mid+90;m.players[11].y=FIELD.center;m.players.slice(6,11).forEach(p=>{p.x=FIELD.right-20;p.y=FIELD.top+20});m.step(.02,[{},{}]);assert(m.players[11].sprinting&&m.players[11].stamina<1,'AI recovery runs must spend stamina like human sprints');
m=new Match();m.state='playing';m.ball.owner=11;m.players[11].x=170;m.players[11].y=FIELD.center;m.ball.x=170;m.ball.y=FIELD.center;m.players.slice(1,6).forEach(p=>p.x=800);m.aiMove(11,m.players[11],pressure(m));assert(m.players[11].aiKick,'AI shot should show a short windup before contact');m.time+=.1;m.aiMove(11,m.players[11],pressure(m));assert.equal(m.ball.owner,null);assert.equal(m.shots[1],1);
const random=Math.random,totals=[];
try{for(const style of ['balanced','counter','press'])for(let difficulty=0;difficulty<4;difficulty++){let shots=0,passes=0,goals=0;for(let run=0;run<4;run++){let seed=123+run*911;Math.random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);m=new Match({duration:120,difficulty,styles:['balanced',style]});m.state='playing';for(let frame=0;frame<9000;frame++)m.step(.02);assert.equal(m.state,'ended');assert(m.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=FIELD.left&&p.x<=FIELD.right&&p.y>=FIELD.top&&p.y<=FIELD.bottom));shots+=m.shots[1];passes+=m.passes[1];goals+=m.score[1]}assert(shots>0,`${style}, difficulty ${difficulty} must create attempts across seeds`);totals.push({style,difficulty,shots,passes,goals})}}finally{Math.random=random}
console.log('PASS: score-driven plans, short-handed cover, two-half give-and-go, transitions and rebound pursuit.');console.log(JSON.stringify({liveAITotals:totals}));
