import {LEAGUES,getTeam,prepareSeason} from './league.mjs';
import {activePlayers,teamName} from './identity.mjs';

const rated=p=>{const a=p.attributes;return Math.round(p.position===0?a.goalkeeping*.75+a.passing*.1+a.speed*.15:p.position<3?a.defense*.45+a.passing*.2+a.speed*.25+a.shooting*.1:p.position<5?a.passing*.4+a.shooting*.2+a.defense*.15+a.speed*.25:a.shooting*.45+a.speed*.3+a.passing*.2+a.defense*.05)};
export const value=p=>+(Math.max(1,(rated(p)-45)*.48)**1.15).toFixed(1);
export const wage=p=>+(value(p)*.12).toFixed(1);
export function windowState(season){const kind=season.week===0?'summer':season.week===7?'winter':null,limit=kind==='summer'?2:kind==='winter'?1:0,used=(season.transfers??[]).filter(t=>t.season===(season.history?.length??0)+1&&t.window===kind).length;return {kind,limit,used,remaining:kind?Math.max(0,limit-used):0}}
export function finances(season){const strength=getTeam(season.teamId).strength,base=+(16+strength*18).toFixed(1),balance=season.balance??base,wages=activePlayers(season,season.teamId).reduce((n,p)=>n+wage(p),0);return {balance:+balance.toFixed(1),wages:+wages.toFixed(1),wageCap:+(14+strength*2).toFixed(1)}}
export function offers(season){const own=season.teamId,league=LEAGUES.find(l=>l.id===season.leagueId),current=activePlayers(season,own);return league.teams.filter(t=>t.id!==own).flatMap(team=>activePlayers(season,team.id).map(p=>{const outgoing=current[p.position],gross=+(value(p)*1.25).toFixed(1),sale=+(value(outgoing)*.75).toFixed(1),fee=+Math.max(1,gross-sale).toFixed(1),allowed=rated(outgoing)>=rated(p)-12;return {id:p.id,from:team.id,name:p.name,position:p.position,rating:rated(p),outgoing:outgoing.name,outgoingId:outgoing.id,fee,wage:wage(p),outgoingWage:wage(outgoing),allowed,reason:allowed?'球员互换 + 现金差额':'卖方拒绝：替代球员实力差距过大'}})).sort((a,b)=>a.position-b.position||b.rating-a.rating)}
export function sign(season,targetId){const next=structuredClone(season);prepareSeason(next);const win=windowState(next);if(!win.remaining)throw new Error('当前没有开放的转会名额');const offer=offers(next).find(o=>o.id===targetId);if(!offer)throw new Error('报价已失效');if(!offer.allowed)throw new Error(offer.reason);const money=finances(next),out=next.playerData[offer.outgoingId],incoming=next.playerData[targetId];if(offer.fee>money.balance)throw new Error('转会费超过可用资金');if(money.wages-wage(out)+wage(incoming)>money.wageCap)throw new Error('签约后工资总额超出上限');const slot=incoming.position,home=next.teamId,away=offer.from;next.rosterIds[home][slot]=targetId;next.rosterIds[away][slot]=out.id;incoming.teamId=home;out.teamId=away;const taken=new Set(activePlayers(next,home).filter(p=>p.id!==targetId).map(p=>p.number));if(taken.has(incoming.number))incoming.number=Array.from({length:99},(_,i)=>i+1).find(n=>!taken.has(n));const awayTaken=new Set(activePlayers(next,away).filter(p=>p.id!==out.id).map(p=>p.number));if(awayTaken.has(out.number))out.number=Array.from({length:99},(_,i)=>i+1).find(n=>!awayTaken.has(n));next.balance=+(money.balance-offer.fee).toFixed(1);next.transfers=[...(next.transfers??[]),{season:(next.history?.length??0)+1,window:win.kind,in:targetId,out:out.id,from:away,to:home,fee:offer.fee,summary:`${incoming.name} 加盟 ${teamName(next,home)}；${out.name} 转会 ${teamName(next,away)}`}];return next}
