import {teamName} from './identity.mjs';
import React,{useState,useRef,useEffect} from 'react';
import {CareerTimeline,SeasonRecap,SignatureMatch} from './story.jsx';
import {TACTIC_NAMES,TACTIC_HINTS} from './tactics.mjs';
import {CareerRolePanel,RoleIdentity,FeedbackCard,ImportantMatch} from './career-role.jsx';
import {getTeam,getLeague,fixtures,standings,roster,currentFixture,playerRows} from './league.mjs';
import {positionLabel,levelProgress,ratingBreakdown} from './career.mjs';
import {TacticPreview} from './experience.jsx';
import {drawPortrait,onSpriteReady} from './player-sprite.mjs';

export function MatchTacticStrip({match}){if(match.practice||match.shootoutMode)return null;return <div className="live-tactical-strip">{[0,1].map(t=>{const plan=match.teamPlan(t);return <span key={t}>{t===0?'己方':'对手'} · {TACTIC_NAMES[plan.style]??'控球推进'}{plan.mentality==='chase'?' · 加强进攻':plan.mentality==='protect'?' · 稳守反击':''}{plan.shortHanded?' · 少人调整':''}</span>})}</div>}
export function MatchTactics({match}){if(match.practice||match.shootoutMode)return null;const names={normal:'常规展开',chase:'加强进攻',protect:'稳守反击'};return <section className='panel match-tactics'><h2>比赛走势与战术</h2>{[0,1].map(t=>{const plan=match.teamPlan(t);return <div key={t}><strong>{match.teams[t]}</strong><span>{TACTIC_NAMES[plan.style]??'控球推进'} · {names[plan.mentality]}{plan.shortHanded?' · 人数不足，保留防线':''}</span></div>})}<p>{TACTIC_HINTS[match.styles[1]]??TACTIC_HINTS.balanced}</p><small>后段根据比分调整前插与压迫；暂停可更换己方战术。</small></section>}

export function ShotContext({match}){if(match.state!=='playing')return null;const id=match.selected[0],p=match.players[id];if(!match.active(id))return <div className="shot-context">已被罚下 · 观看队友完成比赛</div>;const owned=match.ball.owner===id,pressure=match.players.some((q,j)=>q.t!==p.t&&match.active(j)&&Math.hypot(q.x-p.x,q.y-p.y)<55),distance=Math.abs((match.direction(p.t)===1?936:24)-p.x)/10;return <div className={`shot-context ${pressure&&owned?'under-pressure':''}`}><strong>{owned?(match.charge>.45?'蓄力射门':distance<20?'近距离 · 快射可用':'持球 · 鼠标瞄准'):match.pendingShot?'射门已预输入 · 等待接球':match.ball.z>9?'空中球 · 靠近落点后左键接应':'无球 · 跑出接应空间'}</strong><span>{owned?`${pressure?'近身受压，横移或传球 · ':''}按住左键蓄力，松开出脚${match.charge>0?' · 力度 '+Math.round(match.charge*100)+'%':''}`:match.careerIndex!==null?'K 呼叫传球 · WASD 跑位':'Q 切人 · WASD 移动'}</span></div>}

function RatingNotes({stat,score,position}){const {rating,entries}=ratingBreakdown(stat,score,position);return <details className="rating-notes"><summary>评分如何得到？</summary><p>基础6.0分，按位置计算贡献；重复动作有上限，最终评分限制在4—10。</p>{entries.length?entries.map(([name,value])=><div key={name}><span>{name}</span><b>{value>0?'+':''}{value.toFixed(2)}</b></div>):<p>本场暂无有效贡献记录，保留基础出场评分。</p>}<p>最终 {rating.toFixed(1)} 分 · 进攻尝试本身不会因射偏扣分。</p></details>}

function MatchMemories({career,onMemory,onReport,onSignature}){const rows=(career.history??[]).map((r,i)=>({...r,matchId:r.matchId??Math.max(1,career.stats.appearances-career.history.length+i+1)})),[chosen,setChosen]=useState(null),selected=rows.find(r=>r.matchId===chosen)??rows.at(-1),saved=career.memories??[],isSaved=saved.some(r=>r.matchId===selected?.matchId);return <section className="panel match-memories"><h2>值得记住的比赛</h2><p>首秀、首次进球／助攻、帽子戏法和决赛自动收藏。最多30场；收藏保存射门、事件和统计，不保存完整热区。</p>{selected&&<div className="memory-picker"><label>选择比赛<select value={selected.matchId} onChange={e=>setChosen(+e.target.value)}>{rows.slice().reverse().map(r=><option key={r.matchId} value={r.matchId}>第{r.season}赛季 · {r.opponent} · {r.score.join(':')}{r.report?'':' · 仅摘要'}</option>)}</select></label><button className="subtle" disabled={!onMemory||!isSaved&&(!selected.report||saved.length>=30)} onClick={()=>onMemory(selected.matchId)}>{isSaved?'取消收藏':'收藏本场'}</button></div>}<p>{saved.length} / 30 场已收藏{saved.length>=30?' · 已满，可取消已有收藏后重新选择':''}</p>{saved.length?saved.slice().reverse().map(r=><div className="memory-entry" key={r.matchId}><div><strong>{r.reasons.join(' · ')}</strong><p>第{r.season}赛季 · {r.competition==='cup'?'欧洲冠军杯':'联赛'} · {r.opponent} · {r.score.join(' : ')}</p><small>{r.goals}球 / {r.assists}助攻 · 评分{r.rating}</small></div><div className="memory-actions"><button className="subtle" aria-pressed={career.signatureMatchId===r.matchId} disabled={!onSignature} onClick={()=>onSignature(career.signatureMatchId===r.matchId?null:r.matchId)}>{career.signatureMatchId===r.matchId?'撤下主页代表作':'设为主页代表作'}</button><button className="subtle" disabled={!r.report} onClick={()=>onReport(r.report)}>打开收藏复盘 ↗</button><button className="subtle" disabled={!onMemory} onClick={()=>onMemory(r.matchId)}>取消这场收藏</button></div></div>):<p>完成首秀，建立你的第一份比赛记忆。</p>}</section>}

export function trapDialog(event){if(event.key!=='Tab')return;const controls=[...event.currentTarget.querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')].filter(n=>n.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}

export function PixelPlayer({team,number=10,appearance={},back=false,keeper=false}){
  const skin=appearance.skin??'#ebbd89',hair=appearance.hair??'#302b24',kit=keeper?'#e6ca64':team?.color??'#85c9ed',trim=team?.secondary??'#f2f2ea',ink=[1,3,5].reduce((sum,i,j)=>sum+parseInt(kit.slice(i,i+2),16)*[.299,.587,.114][j],0)>145?'#14222c':'#f2f2ea';
  const canvas=useRef(null),shoes=appearance.shoes??'#f47b28',hairstyle=appearance.hairstyle??0,sleeve=appearance.sleeve??'short';
  useEffect(()=>{if(back)return;const paint=()=>canvas.current&&drawPortrait(canvas.current,{kit,skin,hair,shoes,hairstyle,sleeve,number,ink});paint();return onSpriteReady(paint)},[back,kit,skin,hair,shoes,hairstyle,sleeve,number,ink]);
  if(!back)return <canvas ref={canvas} className="pixel-player" width="120" height="180" role="img" aria-label={`${team?.name??'球员'} ${number}号正面`} style={{imageRendering:'pixelated'}}/>;
  return <svg className="pixel-player" viewBox="0 0 120 180" role="img" aria-label={`${team?.name??'球员'} ${number}号${back?'背面':'正面'}`} shapeRendering="crispEdges">
    <ellipse cx="60" cy="168" rx="40" ry="7" fill="#080f17"/>
    <path d="M39 112h17v38H39zm25 0h17v38H64z" fill={skin}/><path d="M39 136h17v22H39zm25 0h17v22H64z" fill={kit}/>
    <path d="M32 156h24v9H29v-5zm32 0h21l7 4v5H64z" fill={appearance.shoes??'#f2f2ea'}/>
    <path d="M34 57h52v61H34z" fill={kit}/><path d="M34 110h52v15H34z" fill="#192936"/>
    <path d="M24 61h10v43H24zm62 0h10v43H86z" fill={skin}/>
    <path d={`M24 57h10v${appearance.sleeve==='long'?36:15}H24zm62 0h10v${appearance.sleeve==='long'?36:15}H86z`} fill={kit}/>
    {appearance.sleeve==='band'&&<path d="M24 84h10v5H24" fill="#f2f2ea"/>}
    <path d="M48 45h24v16H48zM40 17h40v31H40zM35 27h5v15h-5zm45 0h5v15h-5z" fill={skin}/>
    {appearance.hairstyle!==5&&<path d={appearance.hairstyle===3?'M38 12h44v13H38zm0 12h7v33h-7z':appearance.hairstyle===4?'M40 15h40v5H40z':'M38 12h44v14H38zm0 12h7v8h-7zm37 0h7v8h-7z'} fill={hair}/>}
    {!back&&<><path d="M48 31h4v4h-4zm20 0h4v4h-4z" fill="#222833"/><path d="M55 42h10v2H55z" fill="#9a634f"/></>}
    <path d="M48 58l12 8 12-8" stroke={trim} strokeWidth="4" fill="none"/>
    <text x="60" y="98" textAnchor="middle" fill={ink} fontFamily="monospace" fontSize="29" fontWeight="900">{number}</text>
    <path d="M34 62h5v46h-5z" fill="#ffffff18"/>
  </svg>;
}

export function LockerRoom(){return <svg className="locker-room" viewBox="0 0 700 400" preserveAspectRatio="xMidYMid slice" aria-hidden="true" shapeRendering="crispEdges"><path fill="#131e2b" d="M0 0h700v400H0z"/><path fill="#1e2d3b" d="M0 50h530v245H0z"/>{[0,1,2,3,4,5].map(i=><g key={i}><path d={`M${i*86+12} 64h72v190h-72z`} fill="#172431" stroke="#304555" strokeWidth="3"/><path d={`M${i*86+30} 75h37v4h-37zm0 9h37v4h-37zm0 9h37v4h-37z`} fill="#304555"/><path d={`M${i*86+69} 160h4v12h-4z`} fill="#7191a4"/></g>)}<path d="M15 275h510v12H15zm20 12h12v52H35zm454 0h12v52h-12z" fill="#53646e"/><path d="M0 345h700v55H0z" fill="#101922"/><path d="M550 40h135v260H550z" fill="#749aac"/><path d="M564 50h107v220H564z" fill="#273e4b"/><path d="M564 205h107v65H564z" fill="#466750"/><path d="M565 211h107v3H565z" fill="#c8dbcf"/><path d="M548 298h140l12 47H530z" fill="#243a46"/><path d="M10 25h505v5H10z" fill="#7199ad"/></svg>}

function flatten(nodes){return React.Children.toArray(nodes).flatMap(n=>n?.type===React.Fragment?flatten(n.props.children):[n])}
function label(node){const children=flatten(node?.props?.children);return children.find(c=>c?.props?.className==='panel-label')?.props.children??''}
function category(n){if(n?.props?.uiSection)return n.props.uiSection;const name=n?.type?.name,cls=n?.props?.className??'',title=String(label(n));
  if(name==='PlayerCustomization')return 'player';
  if(name==='CareerJournal'||name==='LeagueExplorer'||title.includes('DATA')||title.includes('TOTALS'))return 'data';
  if(name==='HonorsPanel')return 'legacy';
  if(name==='CupPanel'||title.includes('RESULTS')||title.includes('LOG'))return 'schedule';
  if(cls.includes('overview')||title.includes('TABLE')||title==='LAST MATCH')return 'overview';
  return 'data';
}

export function HomeSummary({slot}){if(!slot)return <div className="home-summary"><div><h3>俱乐部</h3><p>亲自比赛或模拟，带领球队争冠。</p></div><div><h3>MyCareer</h3><p>创造专属球员，从首秀开始成长。</p></div><div><h3>训练场</h3><p>练习射门、传中和空中终结。</p></div></div>;const season=slot.season,career=slot.player,games=season.results.filter(r=>r.home===season.teamId||r.away===season.teamId);return <div className="home-summary"><div><h3>近期状态</h3><strong>{games.slice(-5).map(r=>{const i=r.home===season.teamId?0:1;return r.score[i]>r.score[1-i]?'W':r.score[i]===r.score[1-i]?'D':'L'}).join(' · ')||'等待首秀'}</strong><p>{games.length} 场联赛已完成</p></div><div><h3>{career?'生涯贡献':'赛季进球'}</h3><strong>{career?`${career.stats.goals} G / ${career.stats.assists} A`:games.reduce((n,r)=>n+r.score[r.home===season.teamId?0:1],0)}</strong><p>{career?`${career.stats.appearances} 次出场 · LV.${career.level}`:'包含亲自比赛与模拟'}</p></div><div><h3>荣誉篇章</h3><strong>{career?.honors?.at(-1)??'新的旅程'}</strong><p>第 {(season.history?.length??0)+1} 赛季 · 已完成赛季 {season.history?.length??0}</p></div></div>}

export function SeasonWorkspace({season,career,children,onReport,onTactic,onPlay,onMemory,onSignature}){
  const [tab,setTab]=useState('overview'),[back,setBack]=useState(false),[selected,setSelected]=useState(0),dirty=useRef(false),[pendingTab,setPendingTab]=useState(null);
  if(!season)return children;
  const root=React.Children.only(children),sections=flatten(root.props.children),panels=sections.flatMap(s=>flatten(s.props?.children));
  const team=getTeam(season.teamId),names=roster(season.teamId).map((n,i)=>season.playerData?.[season.rosterIds?.[season.teamId]?.[i]]?.name??season.names?.[`${season.teamId}:${i}`]??n),games=season.results.filter(r=>r.home===season.teamId||r.away===season.teamId),rank=standings(season).findIndex(r=>r.id===season.teamId)+1;
  const hasData=games.length>0||(career?.history?.length??0)>0,nextPair=currentFixture(season);
  const tabs=[['overview','总览'],['player',career?'我的球员':'球队与战术'],['schedule','赛程与杯赛'],['data',career?'表现数据':'赛事数据'],['legacy',career?'生涯档案':'荣誉档案']];
  return <div className="season-workspace" style={{'--team-color':team.color}}><nav className="mode-nav" aria-label={career?'生涯导航':'俱乐部导航'}>{tabs.map(([id,name])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>{if(id===tab||!dirty.current)setTab(id);else setPendingTab(id)}}>{name}</button>)}</nav>
    {tab==='overview'&&<><div className="season-identity"><div><span>{getLeague(season.leagueId).name} / 第 {(season.history?.length??0)+1} 赛季</span><h2>{career?career.name:team.name}</h2><p>{career?`${career.number}号 · ${positionLabel(career.position)} · LV.${career.level}`:'六人阵容 · 你的球队，你的比赛日'}</p>{nextPair&&onPlay&&<div className='identity-next'><p>下一场 · {teamName(season,nextPair.find(id=>id!==season.teamId))}</p><button className='primary' onClick={onPlay}>{hasData?'准备下一场':'开始首秀'} →</button></div>}</div><div className="identity-art"><LockerRoom/><PixelPlayer team={team} number={career?.number??10} appearance={career?.appearance}/></div></div><div className="dashboard-ribbon"><div><strong>{games.length?rank:'—'}</strong><span>联赛排名</span></div><div><strong>{career?.stats.goals??games.reduce((a,r)=>a+r.score[r.home===season.teamId?0:1],0)}</strong><span>{career?'生涯进球':'联赛进球'}</span></div><div><strong>{career?.stats.assists??games.reduce((a,r)=>a+r.score[r.home===season.teamId?1:0],0)}</strong><span>{career?'生涯助攻':'联赛失球'}</span></div><div><strong>{games.slice(-5).map(r=>{const i=r.home===season.teamId?0:1;return r.score[i]>r.score[1-i]?'W':r.score[i]===r.score[1-i]?'D':'L'}).join(' ')||'等待首秀'}</strong><span>最近五场</span></div></div></>}
    {tab==='overview'&&career&&<><CareerRolePanel career={career} season={season}/><ImportantMatch career={career} season={season}/><ImportantMatch career={career} season={season} competition='cup'/><CareerHighlights career={career} onReport={onReport}/><SignatureMatch career={career} onReport={onReport}/><SeasonRecap key={career.name} career={career} season={season} onReport={onReport}/></>}
    {tab==='player'&&<><div className="player-stage"><LockerRoom/><PixelPlayer team={team} number={career?.number??(season.playerData?.[season.rosterIds?.[season.teamId]?.[selected]]?.number??(selected===0?1:selected+5))} appearance={career?.appearance} back={back} keeper={!career&&selected===0}/><div><span>PLAYER IDENTITY</span><h2>{career?.name??names[selected]}</h2><p>{teamName(season,team.id)} · {career?positionLabel(career.position):['门将','后卫','后卫','中场','中场','前锋'][selected]}</p><button className="subtle" onClick={()=>setBack(!back)}>查看{back?'正面':'背面'} ↻</button>{<div className="ability-bars">{Object.entries(career?.attributes??season.playerData?.[season.rosterIds?.[season.teamId]?.[selected]]?.attributes??{}).filter(([k])=>k!=='goalkeeping'||!career&&selected===0).map(([k,v])=><div key={k}><span>{{shooting:'射门',passing:'传球',defense:'防守',goalkeeping:'守门'}[k]} <b>{v}</b></span><meter min="0" max="99" value={v}/></div>)}</div>}</div></div>{!career&&<div className="team-selection"><div className="formation-board" aria-label="六人阵容">{[[12,50],[32,25],[32,75],[58,25],[58,75],[82,50]].map(([x,y],i)=><button key={i} style={{left:x+'%',top:y+'%'}} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{season.playerData?.[season.rosterIds?.[season.teamId]?.[i]]?.number??(i===0?1:i+5)}</button>)}</div><div className="roster-list">{names.map((n,i)=><button key={i} aria-pressed={selected===i} onClick={()=>setSelected(i)}><b>{season.playerData?.[season.rosterIds?.[season.teamId]?.[i]]?.number??(i===0?1:i+5)}</b>{n}<small>{['门将','后卫','后卫','中场','中场','前锋'][i]}</small></button>)}</div><TacticPreview value={season.tactic??'balanced'} onChange={onTactic}/></div>}</>}
    {tab==='schedule'&&<Schedule season={season} onReport={onReport}/>}
    {tab==='data'&&!hasData&&<section className='panel debut-data'><h2>你的第一份比赛档案，等待开场。</h2><p>完成首场后，查看射门分布、球员热区、逐场表现和成长记录。</p><ul><li>复盘：找到进球和失球的原因</li><li>成长：追踪射门、传球、防守变化</li><li>档案：收藏你的代表作</li></ul>{onPlay&&nextPair&&<button className='primary' onClick={onPlay}>开始首秀 →</button>}</section>}
    {tab==='data'&&hasData&&<><ScoreChart season={season} onReport={onReport}/><RankChart season={season} onReport={onReport}/><PlayerCompare season={season}/>{career&&<GrowthChart career={career} onReport={onReport}/>}</>}
    {tab==='legacy'&&<div className="archive-intro"><span>THE STORY SO FAR</span><h2>{career?'从首秀，到你的代表作。':'每一个赛季，都有自己的故事。'}</h2><p>已完成 {career?.stats.appearances??games.length} 场比赛 · 记录源于实际比赛与标注的模拟赛果。</p>{career?.honors?.length?<div className="milestone-list">{career.honors.map(n=><span key={n}>★ {n}</span>)}</div>:<p>下一场，就是新篇章的开始。</p>}{career&&<><h3>生涯代表作</h3>{[...(career.history??[])].sort((a,b)=>b.rating-a.rating).slice(0,3).map((r,i)=><button key={i} className="journal-row" disabled={!r.report} onClick={()=>onReport(r.report)}><span>第 {r.season} 赛季 · {r.opponent}<small>{r.goals} 进球 · {r.assists} 助攻 · {r.score.join(' : ')}</small></span><b>{r.rating}</b></button>)}</>}</div>}
    {tab==='legacy'&&career&&<><CareerRolePanel career={career} season={season}/><CareerTimeline career={career} onReport={onReport}/><MatchMemories career={career} onMemory={onMemory} onSignature={onSignature} onReport={onReport}/></>}
    {tab==='legacy'&&season.history?.length>0&&<section className="panel schedule-panel"><h2>已完成赛季</h2>{season.history.map((r,i)=><div className="season-year" key={i}><h3>第 {i+1} 赛季 · {r.team??r.league}</h3><p>联赛冠军：{getTeam(r.champion)?.name??r.champion} · 欧洲冠军杯：{r.cupChampion?getTeam(r.cupChampion)?.name??r.cupChampion:'未夺冠 / 未记录'}</p>{r.summary?<p>{r.summary.wins} 胜 {r.summary.draws} 平 {r.summary.losses} 负 · 进失球 {r.summary.goalsFor}:{r.summary.goalsAgainst} · 门将扑救 {r.summary.saves}</p>:<p>旧赛季未保存完整统计，荣誉仍保留。</p>}</div>)}</section>}
    {tab==='legacy'&&career&&<section className="panel schedule-panel"><h2>历年生涯年鉴</h2><p>从本次更新起永久累计赛季汇总；旧比赛详情仅展示已保存内容。</p>{Object.entries(career.seasonLedger??{}).map(([year,r])=><div className="schedule-row" key={year}><span>赛季 {year}</span><strong>{r.appearances} 次出场</strong><b>{(r.ratingTotal/r.appearances).toFixed(1)}</b><span>{r.goals} 球 / {r.assists} 助攻</span><span>{r.wins}胜 {r.draws}平 {r.losses}负</span></div>)}{!Object.keys(career.seasonLedger??{}).length&&<p>下一场比赛结束后，建立第一份赛季年鉴。</p>}</section>}
    {pendingTab&&<div className="modal"><section className="panel settings-dialog" role="dialog" aria-modal="true" aria-label="未保存的个性化" onKeyDown={trapDialog}><h2>个性化尚未保存</h2><p>离开会放弃当前预览。可以返回继续编辑并保存。</p><button autoFocus className="primary" onClick={()=>setPendingTab(null)}>继续编辑</button><button className="subtle" onClick={()=>{setTab(pendingTab);setPendingTab(null)}}>放弃修改并离开</button></section></div>}<div className={`workspace-panels tab-${tab}`}>{panels.filter(n=>category(n)===tab&&(tab!=='data'||hasData)).map((n,i)=><React.Fragment key={i}>{category(n)==='player'?React.cloneElement(n,{onDirty:value=>{dirty.current=value}}):n}</React.Fragment>)}</div>
    {tab==='overview'&&!games.length&&<p className="first-match-note">还没有比赛数据。完成首场比赛后，这里会记录状态、成长和比赛故事。</p>}
  </div>;
}

function CareerHighlights({career,onReport}){const recent=(career.history??[]).slice(-5);return <div className="career-highlights"><section className="panel"><h3>最近五场 · 评分</h3>{recent.length?<div className="form-points">{recent.map((r,i)=><button key={i} disabled={!r.report} onClick={()=>onReport(r.report)} aria-label={`${r.opponent}，评分 ${r.rating}，查看复盘`}><b>{r.rating}</b><i style={{height:r.rating/10*70+'px'}}/><small>{r.opponent}</small></button>)}</div>:<p>等待首秀。下一场比赛后开始记录表现。</p>}</section><section className="panel"><h3>我的足球故事</h3><strong>{career.honors?.at(-1)??'职业生涯，从第一声哨响开始。'}</strong><p>{career.lastMatch?`上一场 ${career.lastMatch.goals} 进球 · ${career.lastMatch.assists} 助攻 · +${career.lastMatch.xpGain} XP`:'完成位置目标，帮助球队，也让自己成长。'}</p><small>LV.{career.level} · 距离下一级还需 {levelProgress(career).remaining} XP</small><FeedbackCard stat={career.lastMatch} position={career.position} showPromotion/></section></div>}

function GrowthChart({career,onReport}){const rows=(career.history??[]).filter(r=>r.shooting!==undefined).slice(-60),[metric,setMetric]=useState('shooting'),[chosen,setChosen]=useState(null),selected=rows[chosen],names={shooting:'射门',passing:'传球',defense:'防守'},x=i=>45+i/Math.max(1,rows.length-1)*620,y=n=>180-n/99*155;return <section className="panel score-chart"><div className="chart-heading"><h2>能力成长轨迹</h2><select aria-label="成长能力指标" value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(names).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></div><p>最近60条能力快照 · 点击节点查看表现与升级 · 上限99</p>{rows.length?<><svg className="growth-chart" viewBox="0 0 720 225" role="group" aria-label={names[metric]+'逐场成长'}>{[0,50,99].map(n=><g key={n}><path d={'M35 '+y(n)+'H690'} stroke="#405363"/><text x="4" y={y(n)+4} fill="#bdcbd5">{n}</text></g>)}<polyline points={rows.map((r,i)=>x(i)+','+y(r[metric])).join(' ')} fill="none" stroke="#caff70" strokeWidth="3"/>{rows.map((r,i)=><g key={i}><circle cx={x(i)} cy={y(r[metric])} r={chosen===i?8:5} fill="#caff70" role="button" tabIndex={0} aria-label={r.opponent+'，'+names[metric]+r[metric]} aria-pressed={chosen===i} onClick={()=>setChosen(i)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();setChosen(i)}}}/>{(i===0||i===rows.length-1)&&<text x={x(i)} y="212" textAnchor="middle" fill="#bdcbd5">{r.matchId?`第${r.matchId}场`:`记录${i+1}`}</text>}</g>)}</svg>{selected&&<div className="chart-selection" role="status"><strong>第{selected.season}赛季 · {selected.opponent} · LV.{selected.level}</strong><span>{names[metric]} {selected[metric]} · 本场 +{selected.growth?.[metric]??0} · 评分 {selected.rating}</span><button className="subtle" disabled={!selected.report} onClick={()=>onReport(selected.report)}>打开本场复盘 ↗</button></div>}</>:<p>完成首场后开始记录能力变化。</p>}</section>}

function PlayerCompare({season}){const rows=playerRows(season),[a,setA]=useState(''),[b,setB]=useState('');if(!rows.length)return <section className="panel score-chart"><h2>球员数据对比</h2><p>首轮结束后，可选择两名球员比较累计表现。</p></section>;const key=r=>`${r.teamId}:${r.index}`,first=rows.find(r=>key(r)===a)??rows.find(r=>r.teamId===season.teamId)??rows[0],second=rows.find(r=>key(r)===b)??rows.find(r=>r.teamId!==first.teamId)??rows[1]??rows[0];return <section className="panel score-chart"><h2>球员数据对比</h2><p>相同单位的累计总量；包含模拟数据，不等同于能力评级或每 90 分钟效率。</p><div className="report-filters">{[[first,setA,'对比球员一'],[second,setB,'对比球员二']].map(([r,set,label])=><select key={label} aria-label={label} value={key(r)} onChange={e=>set(e.target.value)}>{rows.map(p=><option key={key(p)} value={key(p)}>{p.name} · {p.team}</option>)}</select>)}</div>{[['goals','进球'],['assists','助攻'],['passesCompleted','成功传球'],['tackles','成功抢断'],['saves','扑救']].map(([k,n])=>{const max=Math.max(1,first[k]??0,second[k]??0);return <div className="comparison-row" key={k}><b>{first[k]??0}</b><div><i style={{width:(first[k]??0)/max*100+'%'}}/></div><span>{n}</span><div><i style={{width:(second[k]??0)/max*100+'%'}}/></div><b>{second[k]??0}</b></div>})}</section>}

function RankChart({season,onReport}){const [compare,setCompare]=useState(getLeague(season.leagueId).teams.find(t=>t.id!==season.teamId).id),[chosen,setChosen]=useState(null);const rows=Array.from({length:season.week},(_,i)=>standings({...season,results:season.results.filter(r=>r.week<=i)})),round=chosen===null?null:season.results.find(r=>r.week===chosen&&(r.home===season.teamId||r.away===season.teamId));function choose(i){setChosen(i)}return <section className="panel score-chart"><div className="chart-heading"><h2>排名走势对比</h2><select aria-label="排名对比球队" value={compare} onChange={e=>setCompare(e.target.value)}>{getLeague(season.leagueId).teams.filter(t=>t.id!==season.teamId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><p className="data-legend"><span><i style={{background:'var(--team-color)'}}/>{teamName(season,season.teamId)} · 实线</span><span><i style={{background:'#e6c986'}}/>{teamName(season,compare)} · 虚线</span></p><p>纵轴排名 · 横轴轮次 · 点击节点查看积分与赛果</p>{rows.length?<><svg viewBox="0 0 720 225" className="rank-chart" role="group" aria-label="逐轮排名对比">{[1,4,8].map(n=><g key={n}><path d={'M35 '+(20+(n-1)*24)+'H690'} stroke="#405363"/><text x="5" y={25+(n-1)*24} fill="#bdcbd5">{n}</text></g>)}{[season.teamId,compare].map((id,j)=><g key={id}><polyline fill="none" stroke={j?'#e6c986':'var(--team-color)'} strokeDasharray={j?'7 5':undefined} strokeWidth="3" points={rows.map((r,i)=>(45+i/Math.max(1,rows.length-1)*630)+','+(20+r.findIndex(t=>t.id===id)*24)).join(' ')}/>{rows.map((r,i)=><circle key={i} cx={45+i/Math.max(1,rows.length-1)*630} cy={20+r.findIndex(t=>t.id===id)*24} r={chosen===i?7:5} fill={j?'#e6c986':'var(--team-color)'} role="button" tabIndex={0} aria-pressed={chosen===i} aria-label={'第'+(i+1)+'轮，'+teamName(season,id)+'，第'+(r.findIndex(t=>t.id===id)+1)+'名'} onClick={()=>choose(i)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();choose(i)}}}/>)}</g>)}{rows.map((r,i)=><text key={i} x={45+i/Math.max(1,rows.length-1)*630} y="214" textAnchor="middle" fill="#bdcbd5">{i+1}</text>)}</svg>{chosen!==null&&<div className="chart-selection" role="status">{[season.teamId,compare].map(id=>{const r=rows[chosen].find(t=>t.id===id);return <span key={id}>{r.name} · 第{rows[chosen].indexOf(r)+1}名 · {r.points}分</span>})}{round&&<><strong>{teamName(season,round.home)} {round.score.join(' : ')} {teamName(season,round.away)}</strong><span>{round.source==='simulated'?'电脑模拟':'实际比赛'}</span><button className="subtle" disabled={!round.report} onClick={()=>onReport(round.report)}>打开本场复盘 ↗</button></>}</div>}</>:<p>首轮结束后显示排名变化。</p>}</section>}

export function Postmatch({match,career,onBack,onReport,onNews,saveError,formal,season}){const [tab,setTab]=useState('result');return <div className="modal postmatch-modal"><section className="panel postmatch-dialog" role="dialog" aria-modal="true" aria-labelledby="postmatch-title" onKeyDown={trapDialog}><span>FULL TIME / 比赛结束</span><h2 id="postmatch-title">{match.teams[0]} <b>{match.score.join(' : ')}</b> {match.teams[1]}</h2>{match.shootout&&<p>点球大战 {match.shootout.score.join(' : ')}</p>}<nav className="mode-nav" aria-label="赛后总结">{[['result','赛果'],['performance',career?'我的表现':'球队表现'],['review','复盘']].map(([v,n])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{n}</button>)}</nav>{tab==='result'&&<>{career&&season&&<RoleIdentity career={career} season={season}/>}<FeedbackCard stat={career?.lastMatch?.roleAfter>career?.lastMatch?.roleBefore?career.lastMatch:null} position={career?.position} showPromotion/><div className="postmatch-stats">{[['射门',match.shots],['射正',match.onTarget],['扑救',match.saves],['传球',match.passes],['犯规',match.fouls]].map(([n,v])=><div key={n}><b>{v[0]}</b><span>{n}</span><b>{v[1]}</b></div>)}</div><p role="status">{formal?(saveError?'保存失败，请返回首页导出备份。':'本场已结算并保存至本地存档。'):'快速比赛不计入生涯与联赛。'}</p></>}{tab==='performance'&&(career?.lastMatch?<div><strong className="postmatch-rating">{career.lastMatch.rating}<small>本场评分</small></strong><p>{career.lastMatch.goals} 进球 · {career.lastMatch.assists} 助攻 · +{career.lastMatch.xpGain} XP</p><FeedbackCard stat={career.lastMatch} position={career.position} showPromotion/><RatingNotes stat={career.lastMatch} score={career.lastMatch.score} position={career.position}/><p className='rating-explanation'>经验包括出场基础奖励、有效贡献和位置目标。后期升级所需经验逐渐增加。</p><p>{career.lastMatch.objective?.label} · {career.lastMatch.objective?.complete?'已完成':'未完成'}</p><div className="ability-bars">{Object.entries(career.attributes).map(([k,v])=><div key={k}><span>{{shooting:'射门',passing:'传球',defense:'防守',goalkeeping:'守门'}[k]} {v}（本场 +{career.lastMatch.growth?.[k]??0}）</span><meter min="0" max="99" value={v}/></div>)}</div></div>:<div className="postmatch-stats">{[['传中',match.crosses],['抢断尝试',match.tackles],['黄牌',match.yellows],['红牌',match.reds]].map(([n,v])=><div key={n}><b>{v[0]}</b><span>{n}</span><b>{v[1]}</b></div>)}</div>)}{tab==='review'&&<div><h3>这场比赛，发生在哪里？</h3><p>查看射门方向、力度、门将处理，以及每位球员的上下半场活动热区。</p><button className="subtle" onClick={onReport}>打开互动复盘 ↗</button></div>}{formal&&<button className="primary" onClick={onNews}>阅读赛后新闻 →</button>}<button autoFocus className="subtle" onClick={onBack}>{formal?'返回赛季总览':'再踢一场'} →</button></section></div>}

function Schedule({season,onReport}){const [scope,setScope]=useState('all');const own=fixtures(getLeague(season.leagueId)).map((round,week)=>({week,pair:round.find(p=>p.includes(season.teamId))}));return <section className="panel schedule-panel"><h2>比赛日历</h2><div className="mode-nav">{[['all','全部'],['next','未赛'],['done','已赛']].map(([v,n])=><button key={v} aria-pressed={scope===v} className={scope===v?'active':''} onClick={()=>setScope(v)}>{n}</button>)}</div>{own.filter(r=>scope==='all'||(scope==='next'?r.week>=season.week:r.week<season.week)).map(({week,pair})=>{const result=season.results.find(r=>r.week===week&&r.home===pair[0]&&r.away===pair[1]);return <div className={`schedule-row ${week===season.week?'next-fixture':''}`} key={week}><span>第 {week+1} 轮<small>{pair[0]===season.teamId?'主场':'客场'}</small></span><strong>{teamName(season,pair[0])}</strong><b>{result?result.score.join(' : '):'VS'}</b><strong>{teamName(season,pair[1])}</strong><button className="subtle" disabled={!result?.report} onClick={()=>onReport(result.report)}>{result?result.source==='simulated'?'模拟赛果':result.report?'复盘 ↗':'已赛':'待赛'}</button></div>})}</section>}

function ScoreChart({season,onReport}){const [metric,setMetric]=useState('goals'),[chosen,setChosen]=useState(null);const rows=season.results.filter(r=>r.home===season.teamId||r.away===season.teamId),max=Math.max(1,...rows.flatMap(r=>metric==='goals'?r.score:r.stats?.[metric]??[])),selected=rows[chosen];return <section className="panel score-chart"><div className="chart-heading"><h2>赛季攻防轨迹</h2><select aria-label="赛季图表指标" value={metric} onChange={e=>setMetric(e.target.value)}>{[['goals','进球 / 失球'],['shots','射门'],['saves','扑救'],['passes','传球']].map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></div><p className='data-legend'><span><i style={{background:'var(--team-color)'}}/>{teamName(season,season.teamId)}</span><span><i style={{background:'#71808a'}}/>对手</span>点击轮次查看赛果</p>{rows.length?<div className="bar-chart">{rows.map((r,i)=>{const side=r.home===season.teamId?0:1,values=metric==='goals'?r.score:r.stats?.[metric];return <button key={i} aria-pressed={chosen===i} aria-label={`第 ${r.week+1} 轮，${values?values[side]+' 比 '+values[1-side]:'未记录'}`} onClick={()=>setChosen(i)}><div>{values?.map((_,j)=><i key={j} style={{height:Math.max(2,values[j===0?side:1-side]/max*100)+'%',background:j===0?'var(--team-color)':'#71808a'}}/>)??<span>—</span>}</div><small>{r.week+1}</small></button>})}</div>:<p className="empty-data">首场比赛后显示逐轮数据，不补造历史记录。</p>}{selected&&<div className="chart-selection" role="status"><strong>{teamName(season,selected.home)} {selected.score.join(' : ')} {teamName(season,selected.away)}</strong><span>{selected.source==='simulated'?'电脑模拟 · 无空间轨迹':'实际比赛'}</span><button className="subtle" disabled={!selected.report} onClick={()=>onReport(selected.report)}>打开本场复盘 ↗</button></div>}</section>}

export function Prematch({season,career,opponentStyle,difficulty,duration,onDifficulty,onDuration,difficulties,onStart,onClose}){const pair=season&&currentFixture(season),team=season?getTeam(season.teamId):null,opponent=pair&&getTeam(pair.find(id=>id!==season.teamId));return <div className="modal" onClick={onClose}><section className="prematch-dialog panel" role="dialog" aria-modal="true" aria-labelledby="prematch-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{trapDialog(e);if(e.key==='Escape')onClose()}}><span>MATCHDAY / 准备上场</span><h2 id="prematch-title">{teamName(season,team?.id)??'蓝队'} <small>VS</small> {teamName(season,opponent?.id)??'红队'}</h2><div className="prematch-kits"><PixelPlayer team={team} number={career?.number??10} appearance={career?.appearance}/><b>VS</b><PixelPlayer team={opponent??{color:'#db7265',secondary:'#faf5ed'}} number={9}/></div><p>{career?`只控制 ${career.name} · ${career.number}号 · ${positionLabel(career.position)}`:'控制全队 · K 传球 · Q 切换球员'}</p>{career&&season&&<><RoleIdentity career={career} season={season}/><ImportantMatch career={career} season={season}/></>}<div className='prematch-scout'><h3>对手怎么踢？</h3><TacticPreview value={opponent?.style??opponentStyle??'balanced'}/><p>{TACTIC_HINTS[opponent?.style??opponentStyle??'balanced']}</p></div><label htmlFor="prematch-ai">对手 AI 强度</label><select autoFocus id="prematch-ai" value={difficulty} onChange={e=>onDifficulty(+e.target.value)}>{difficulties.map((n,i)=><option value={i} key={i}>{n}</option>)}</select><p className='difficulty-explanation'>{['留出观察空间，基本追防与接应。','更快判断出球，尝试传跑配合。','协同压迫、封传球线路、盯防威胁接应。','反应更快，压迫人数更多；同样遵守比赛规则。'][difficulty]}</p><label htmlFor="prematch-duration">实际比赛时长</label><select id="prematch-duration" value={duration} onChange={e=>onDuration(+e.target.value)}>{[120,180,300].map(n=><option key={n} value={n}>{n/60} 分钟 · 模拟 90 分钟</option>)}</select><p>WASD 移动 · 鼠标瞄准 · 按住左键蓄力，松开射门<br/>Shift 冲刺 · J 传中 · L 抢断 · Esc 暂停</p><div className="fixture-actions"><button className="subtle" onClick={onClose}>返回</button><button className="primary" onClick={onStart}>准备好了，开球 →</button></div></section></div>}
